### ISSUE TITLE
I want to know how to use ESP-IDF debugger (VSC-1198)

### ISSUE THREAD

**Issue by Ashutosh-017** [espressif/vscode-esp-idf-extension#1053]
### OS

Windows

### Operating System version

Windows 10

### Visual Studio Code version

1.82.1

### ESP-IDF version

5.1.1

### Python version

3.8.7

### Doctor command output

DEBUG_ADAPTER_STARTED
2023-09-28 14:33:28,451 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_STARTED

[Debug Adapter]
DEBUG_ADAPTER_READY2CONNECT
2023-09-28 14:33:28,451 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_READY2CONNECT

[Debug Adapter]
DEBUG_ADAPTER_STOPPED
2023-09-28 14:33:43,453 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_STOPPED

[Stopped] : ESP-IDF Debug Adapter

### Extension

Output of debug console 
Debug adapter -> Extension: DEBUG_ADAPTER_STARTED
Debug adapter -> Extension: DEBUG_ADAPTER_READY2CONNECT

### Description

When ever I try to run debugger then this message is pop up out 
"Fail to init debug Adapter"

### Debug Message

```plain
Debug adapter -> Extension: DEBUG_ADAPTER_STARTED
Debug adapter -> Extension: DEBUG_ADAPTER_READY2CONNECT
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
Have you read the tutorials and setup and the extension ?

1. https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/tutorial/install.md
2. https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/tutorial/basic_use.md
3. https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/tutorial/debugging.md

**Comment by Ashutosh-017** [comment]
@brianignacio5 Yes I do read all these documents I am able build code run code. I have created a MQTTS related project and a BLE related project everything work fine. I only want to know how to use debugger please help me

**Comment by brianignacio5** [comment]
What about the (3) ? Is about debugging ? 

In your launch.json, change logLevel to 5 to increase the debug output see what is wrong. Check also the OpenOCD output in the ESP-IDF Output Channel. Any errors ? Did you select the right openOCD config files ?

**Comment by Ashutosh-017** [comment]
Thank you so much for this quick response 
Please have a look on data I provide you. 
**launch.json file content** 
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "espidf",
      "name": "Launch",
      "request": "launch",
      "logLevel": 5
    }
  ]
}
**settings.json** file content 
{
    "C_Cpp.intelliSenseEngine": "default",
    "idf.adapterTargetName": "esp32c3",
    "idf.customExtraPaths": "C:\\Users\\ashutosh\\.espressif\\tools\\xtensa-esp-elf-gdb\\11.2_20220823\\xtensa-esp-elf-gdb\\bin;C:\\Users\\ashutosh\\.espressif\\tools\\riscv32-esp-elf-gdb\\11.2_20220823\\riscv32-esp-elf-gdb\\bin;C:\\Users\\ashutosh\\.espressif\\tools\\xtensa-esp32-elf\\esp-2022r1-11.2.0\\xtensa-esp32-elf\\bin;C:\\Users\\ashutosh\\.espressif\\tools\\xtensa-esp32s2-elf\\esp-2022r1-11.2.0\\xtensa-esp32s2-elf\\bin;C:\\Users\\ashutosh\\.espressif\\tools\\xtensa-esp32s3-elf\\esp-2022r1-11.2.0\\xtensa-esp32s3-elf\\bin;C:\\Users\\ashutosh\\.espressif\\tools\\riscv32-esp-elf\\esp-2022r1-11.2.0\\riscv32-esp-elf\\bin;C:\\Users\\ashutosh\\.espressif\\tools\\esp32ulp-elf\\2.35_20220830\\esp32ulp-elf\\bin;C:\\Users\\ashutosh\\.espressif\\tools\\cmake\\3.24.0\\bin;C:\\Users\\ashutosh\\.espressif\\tools\\openocd-esp32\\v0.11.0-esp32-20221026\\openocd-esp32\\bin;C:\\Users\\ashutosh\\.espressif\\tools\\ninja\\1.10.2;C:\\Users\\ashutosh\\.espressif\\tools\\idf-exe\\1.0.3;C:\\Users\\ashutosh\\.espressif\\tools\\ccache\\4.6.2\\ccache-4.6.2-windows-x86_64;C:\\Users\\ashutosh\\.espressif\\tools\\dfu-util\\0.9\\dfu-util-0.9-win64;C:\\Users\\ashutosh\\.espressif\\tools\\esp-rom-elfs\\20220823",
    "idf.customExtraVars": {
        "OPENOCD_SCRIPTS": "C:\\Users\\ashutosh\\.espressif\\tools\\openocd-esp32\\v0.11.0-esp32-20221026/openocd-esp32/share/openocd/scripts",
        "IDF_CCACHE_ENABLE": "1",
        "ESP_ROM_ELF_DIR": "C:\\Users\\ashutosh\\.espressif\\tools\\esp-rom-elfs\\20220823/"
    },
    "idf.espIdfPathWin": "C:\\Users\\ashutosh\\esp\\esp-idf",
    "idf.openOcdConfigs": [
        "board/esp32c3-bridge.cfg"
    ],
    "idf.portWin": "COM3",
    "idf.pythonBinPathWin": "C:\\Users\\ashutosh\\.espressif\\python_env\\idf5.0_py3.8_env\\Scripts\\python.exe",
    "idf.toolsPathWin": "C:\\Users\\ashutosh\\.espressif",
    "idf.flashType": "UART"
}
**Output on output window** 
C:\Users\ashutosh\.espressif\tools\openocd-esp32\v0.11.0-esp32-20221026\openocd-esp32\bin\openocd.exe

C:\Users\ashutosh\.espressif\tools\openocd-esp32\v0.11.0-esp32-20221026\openocd-esp32\bin\openocd.exe

[OpenOCD]
Info : only one transport option; autoselect 'jtag'
Info : esp_usb_jtag: VID set to 0x303a and PID to 0x1002
Info : esp_usb_jtag: capabilities descriptor set to 0x30a
Info : esp_usb_jtag: target chip id set to 5
Warn : Transport "jtag" was already selected
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections

[OpenOCD]
❌ Error: esp_usb_jtag: could not find or open device!

[OpenOCD]
❌ 
Error: Unsupported xlen: -1
Error: Unknown target arch!

[OpenOCD]
[Stopped] : OpenOCD Server
[Debug Adapter]
2023-09-28 17:17:26,788 - Debug Adapter (main) - DEBUG - START_TIME_2023_09_28_17-17-26
2023-09-28 17:17:26,788 - Debug Adapter (main) - DEBUG - Init errors:None
2023-09-28 17:17:26,788 - Debug Adapter (main) - INFO - Working directory: C:\Users\ashutosh\AppData\Local\Programs\Microsoft VS Code

[Debug Adapter]
2023-09-28 17:17:26,788 - Debug Adapter (main) - INFO - Arguments: 
{   'app_flash_off': 65536,
    'board_type': None,
    'cmdfile': None,
    'core_file': (),
    'debug': 5,
    'developer_mode': 'none',
    'device_name': 'esp32c3',
    'elfpath': ('d:\\ESP_PROJECTS\\MQTT_Server\\build\\MQTT_Server.elf',),
    'log_file': 'd:\\ESP_PROJECTS\\MQTT_Server\\debug.log',
    'log_mult_files': None,
    'log_no_debug_console': None,
    'oocd': 'openocd',
    'oocd_args': None,
    'oocd_ip': 'localhost',
    'oocd_mode': 'connect_to_instance',
    'oocd_scripts': None,
    'port': 43474,
    'postmortem': False,
    'tmo_scale_factor': 1,
    'toolchain_prefix': 'riscv32-esp-elf-'}
DEBUG_ADAPTER_STARTED
2023-09-28 17:17:26,788 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_STARTED
2023-09-28 17:17:26,788 - Debug Adapter (main) - INFO - Starting. Cmd: c:\Users\ashutosh\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter_main.py -d 5 -e d:\ESP_PROJECTS\MQTT_Server\build\MQTT_Server.elf -l d:\ESP_PROJECTS\MQTT_Server\debug.log -p 43474 -dn esp32c3 -a 0x10000 -t riscv32-esp-elf-


[Debug Adapter]
2023-09-28 17:17:26,788 - Debug Adapter (main) - INFO - Listening on port 43474
DEBUG_ADAPTER_READY2CONNECT
2023-09-28 17:17:26,788 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_READY2CONNECT

[Debug Adapter]
2023-09-28 17:17:26,788 - Debug Adapter (main) - DEBUG - Got connection

[Debug Adapter]
2023-09-28 17:17:26,788 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Debug adapter -> Extension: DEBUG_ADAPTER_STARTED\n", "source": {}}, "seq": 0}

2023-09-28 17:17:26,788 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Starting. Cmd: c:\\Users\\ashutosh\\.vscode\\extensions\\espressif.esp-idf-extension-1.6.4\\esp_debug_adapter\\debug_adapter_main.py -d 5 -e d:\\ESP_PROJECTS\\MQTT_Server\\build\\MQTT_Server.elf -l d:\\ESP_PROJECTS\\MQTT_Server\\debug.log -p 43474 -dn esp32c3 -a 0x10000 -t riscv32-esp-elf-\n\n", "source": {}}, "seq": 1}

2023-09-28 17:17:26,788 - Debug Adapter (ReaderThread) - DEBUG - read line: >>b'Content-Length: 514\\r\\n'<<


[Debug Adapter]
2023-09-28 17:17:26,788 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Listening on port 43474\n", "source": {}}, "seq": 2}

2023-09-28 17:17:26,788 - Debug Adapter (ReaderThread) - DEBUG - read line: >>b'\\r\\n'<<

2023-09-28 17:17:26,788 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Debug adapter -> Extension: DEBUG_ADAPTER_READY2CONNECT\n", "source": {}}, "seq": 3}

2023-09-28 17:17:26,788 - Debug Adapter(Command Processor) - DEBUG - Got json: {
    "arguments": {
        "adapterID": "espidf",
        "clientID": "vscode",
        "clientName": "Visual Studio Code",
        "columnsStartAt1": true,
        "linesStartAt1": true,
        "locale": "en",
        "pathFormat": "path",
        "supportsArgsCanBeInterpretedByShell": true,
        "supportsInvalidatedEvent": true,
        "supportsMemoryEvent": true,
        "supportsMemoryReferences": true,
        "supportsProgressReporting": true,
        "supportsRunInTerminalRequest": true,
        "supportsStartDebuggingRequest": true,
        "supportsVariablePaging": true,
        "supportsVariableType": true
    },
    "command": "initialize",
    "seq": 1,
    "type": "request"
}

[Debug Adapter]
2023-09-28 17:17:26,788 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Got connection\n", "source": {}}, "seq": 4}

2023-09-28 17:17:26,788 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Got json: {\n    \"arguments\": {\n        \"adapterID\": \"espidf\",\n        \"clientID\": \"vscode\",\n        \"clientName\": \"Visual Studio Code\",\n        \"columnsStartAt1\": true,\n        \"linesStartAt1\": true,\n        \"locale\": \"en\",\n        \"pathFormat\": \"path\",\n        \"supportsArgsCanBeInterpretedByShell\": true,\n        \"supportsInvalidatedEvent\": true,\n        \"supportsMemoryEvent\": true,\n        \"supportsMemoryReferences\": true,\n        \"supportsProgressReporting\": true,\n        \"supportsRunInTerminalRequest\": true,\n        \"supportsStartDebuggingRequest\": true,\n        \"supportsVariablePaging\": true,\n        \"supportsVariableType\": true\n    },\n    \"command\": \"initialize\",\n    \"seq\": 1,\n    \"type\": \"request\"\n}\n", "source": {}}, "seq": 5}


[Debug Adapter]
2023-09-28 17:17:26,806 - Gdb - DEBUG - MI->: -gdb-set mi-async on

[Debug Adapter]
2023-09-28 17:17:27,012 - Gdb - DEBUG - MI<-:
[{'message': 'thread-group-added',
  'payload': {'id': 'i1'},
  'stream': 'stdout',
  'token': None,
  'type': 'notify'},
 {'message': 'done',
  'payload': None,
  'stream': 'stdout',
  'token': None,
  'type': 'result'}]

[Debug Adapter]
2023-09-28 17:17:27,012 - Gdb - INFO - NOTIFY: thread-group-added {'id': 'i1'}
2023-09-28 17:17:27,012 - Gdb - DEBUG - RESULT: done None
2023-09-28 17:17:27,012 - Gdb - DEBUG - MI->: -gdb-set logging file C:\Users\ashutosh\AppData\Local\Temp\gdb_proc.log

[Debug Adapter]
2023-09-28 17:17:27,039 - Gdb - DEBUG - MI<-:
[{'message': 'done',
  'payload': None,
  'stream': 'stdout',
  'token': None,
  'type': 'result'}]

[Debug Adapter]
2023-09-28 17:17:27,039 - Gdb - DEBUG - RESULT: done None
2023-09-28 17:17:27,039 - Gdb - DEBUG - MI->: -gdb-set logging on

[Debug Adapter]
2023-09-28 17:17:27,055 - Gdb - DEBUG - MI<-:
[{'message': 'done',
  'payload': None,
  'stream': 'stdout',
  'token': None,
  'type': 'result'}]

[Debug Adapter]
2023-09-28 17:17:27,055 - Gdb - DEBUG - RESULT: done None
2023-09-28 17:17:27,055 - Gdb - DEBUG - MI->: -gdb-set arch riscv:rv32

[Debug Adapter]
2023-09-28 17:17:27,074 - Gdb - DEBUG - MI<-:
[{'message': None,
  'payload': 'The target architecture is set to \\"riscv:rv32\\".\\n',
  'stream': 'stdout',
  'type': 'console'},
 {'message': 'done',
  'payload': None,
  'stream': 'stdout',
  'token': None,
  'type': 'result'}]

[Debug Adapter]
2023-09-28 17:17:27,074 - Gdb - INFO - CONS: 'The target architecture is set to \\"riscv:rv32\\".\\n'
2023-09-28 17:17:27,074 - Gdb - DEBUG - RESULT: done None
2023-09-28 17:17:27,074 - Debug Adapter (main) - DEBUG - Created gdb object of type: GdbEsp32c3
2023-09-28 17:17:27,074 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Created gdb object of type: GdbEsp32c3\n", "source": {}}, "seq": 6}


[Debug Adapter]
2023-09-28 17:17:27,074 - Gdb - DEBUG - MI->: -file-exec-and-symbols d:/ESP_PROJECTS/MQTT_Server/build/MQTT_Server.elf

[Debug Adapter]
2023-09-28 17:17:29,869 - Gdb - DEBUG - MI<-:
[{'message': 'done',
  'payload': None,
  'stream': 'stdout',
  'token': None,
  'type': 'result'}]

[Debug Adapter]
2023-09-28 17:17:29,869 - Gdb - DEBUG - RESULT: done None
2023-09-28 17:17:29,869 - Gdb - DEBUG - Connecting to 127.0.0.1:3333
2023-09-28 17:17:29,869 - Gdb - DEBUG - MI->: -target-select remote 127.0.0.1:3333

[Debug Adapter]
2023-09-28 17:17:39,885 - Gdb - DEBUG - MI<-:
[]

[Debug Adapter]
2023-09-28 17:17:39,885 - Debug Adapter (main) - ERROR - Failed to wait for completion of command "-target-select remote 127.0.0.1:3333" / 10!
Traceback (most recent call last):
  File "c:\Users\ashutosh\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter\command_processor.py", line 52, in __call__
    on_request(protocol_message)
  File "c:\Users\ashutosh\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter\command_processor.py", line 75, in on_initialize_request
    raise e
  File "c:\Users\ashutosh\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter\command_processor.py", line 70, in on_initialize_request
    self.da.adapter_init()
  File "c:\Users\ashutosh\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter\debug_adapter.py", line 329, in adapter_init
    raise e
  File "c:\Users\ashutosh\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter\debug_adapter.py", line 325, in adapter_init
    self.start_gdb()
  File "c:\Users\ashutosh\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter\debug_adapter.py", line 678, in start_gdb
    raise e
  File "c:\Users\ashutosh\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter\debug_adapter.py", line 675, in start_gdb
    self._gdb.connect()
  File "C:\Users\ashutosh\.espressif\python_env\idf5.0_py3.8_env\lib\site-packages\esp_debug_backend\gdb.py", line 599, in connect
    self.target_select(remote_mode, self._remote_target, tmo=tmo)
  File "C:\Users\ashutosh\.espressif\python_env\idf5.0_py3.8_env\lib\site-packages\esp_debug_backend\gdb.py", line 262, in target_select
    res, _ = self._mi_cmd_run('-target-select %s %s' % (tgt_type, tgt_params),
  File "C:\Users\ashutosh\.espressif\python_env\idf5.0_py3.8_env\lib\site-packages\esp_debug_backend\gdb.py", line 206, in _mi_cmd_run
    raise DebuggerTargetStateTimeoutError(
esp_debug_backend.defs.DebuggerTargetStateTimeoutError: Failed to wait for completion of command "-target-select remote 127.0.0.1:3333" / 10!

[Debug Adapter]
2023-09-28 17:17:39,885 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "response", "request_seq": 1, "success": false, "command": "initialize", "seq": 7, "message": "Failed to init Debug Adapter!", "body": {}}

2023-09-28 17:17:39,887 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Failed to wait for completion of command \"-target-select remote 127.0.0.1:3333\" / 10!\n", "source": {}}, "seq": 8}

2023-09-28 17:17:39,887 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Failed to wait for completion of command \"-target-select remote 127.0.0.1:3333\" / 10!\n", "source": {}}, "seq": 9}


[Debug Adapter]
2023-09-28 17:17:39,889 - Debug Adapter (ReaderThread) - DEBUG - read line: >>b'Content-Length: 79\\r\\n'<<


[Debug Adapter]
2023-09-28 17:17:39,889 - Debug Adapter (ReaderThread) - DEBUG - read line: >>b'\\r\\n'<<

2023-09-28 17:17:39,889 - Debug Adapter(Command Processor) - DEBUG - Got json: {
    "arguments": {
        "restart": false
    },
    "command": "disconnect",
    "seq": 2,
    "type": "request"
}
2023-09-28 17:17:39,889 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Got json: {\n    \"arguments\": {\n        \"restart\": false\n    },\n    \"command\": \"disconnect\",\n    \"seq\": 2,\n    \"type\": \"request\"\n}\n", "source": {}}, "seq": 10}


[Debug Adapter]
2023-09-28 17:17:39,889 - Debug Adapter (main) - DEBUG - Adapter is Stopping...
2023-09-28 17:17:39,889 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Debug Adapter stopped\n", "source": {}}, "seq": 11}

2023-09-28 17:17:39,889 - Debug Adapter (main) - DEBUG - Stopping target poller

[Debug Adapter]
2023-09-28 17:17:39,889 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Adapter is Stopping...\n", "source": {}}, "seq": 12}

2023-09-28 17:17:39,889 - Debug Adapter (main) - DEBUG - Closing the GDB process
2023-09-28 17:17:39,889 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Stopping target poller\n", "source": {}}, "seq": 13}

2023-09-28 17:17:39,889 - Debug Adapter (main) - DEBUG - Closing the Socket

[Debug Adapter]
2023-09-28 17:17:39,889 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Closing the GDB process\n", "source": {}}, "seq": 14}

2023-09-28 17:17:39,889 - Debug Adapter (main) - DEBUG - Stopping of the Writer thread
2023-09-28 17:17:39,889 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Closing the Socket\n", "source": {}}, "seq": 15}


[Debug Adapter]
2023-09-28 17:17:39,889 - Debug Adapter (main) - DEBUG - Stopping of the Reader thread
2023-09-28 17:17:39,889 - Debug Adapter (main) - DEBUG - Adapter is Stopped
DEBUG_ADAPTER_STOPPED
2023-09-28 17:17:39,889 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_STOPPED
2023-09-28 17:17:39,889 - Debug Adapter(Command Processor) - DEBUG - Processed command: disconnect

[Stopped] : ESP-IDF Debug Adapter
**Output on Debug Console**
Debug adapter -> Extension: DEBUG_ADAPTER_STARTED
Starting. Cmd: c:\Users\ashutosh\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter_main.py -d 5 -e d:\ESP_PROJECTS\MQTT_Server\build\MQTT_Server.elf -l d:\ESP_PROJECTS\MQTT_Server\debug.log -p 43474 -dn esp32c3 -a 0x10000 -t riscv32-esp-elf-

Listening on port 43474
Debug adapter -> Extension: DEBUG_ADAPTER_READY2CONNECT
Got connection
Got json: {
    "arguments": {
        "adapterID": "espidf",
        "clientID": "vscode",
        "clientName": "Visual Studio Code",
        "columnsStartAt1": true,
        "linesStartAt1": true,
        "locale": "en",
        "pathFormat": "path",
        "supportsArgsCanBeInterpretedByShell": true,
        "supportsInvalidatedEvent": true,
        "supportsMemoryEvent": true,
        "supportsMemoryReferences": true,
        "supportsProgressReporting": true,
        "supportsRunInTerminalRequest": true,
        "supportsStartDebuggingRequest": true,
        "supportsVariablePaging": true,
        "supportsVariableType": true
    },
    "command": "initialize",
    "seq": 1,
    "type": "request"
}
Created gdb object of type: GdbEsp32c3

Help me how to select right openOCD config file.
I share everything with you please help me

**Comment by brianignacio5** [comment]
See the log 

```
[OpenOCD]
❌ Error: esp_usb_jtag: could not find or open device!

[OpenOCD]
❌
Error: Unsupported xlen: -1
Error: Unknown target arch!
```

there is an openOCD configuration error. Probably because

```json
"idf.openOcdConfigs": [
"board/esp32c3-bridge.cfg"
],
```

is not the correct board for you. Try a different openOCD configuration and make sure openOCD works correctly.

**Comment by Ashutosh-017** [comment]
I am working with ESP32-C3 Mini please tell me how to change openOCD configuration and make openOCD works correctly. 
Thank you

**Comment by Ashutosh-017** [comment]
@brianignacio5 On this page https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/tutorial/debugging.md
**I read this line** 
Choosing esp32c3 as IDF_TARGET will set idf.openOCDConfigs to ["board/esp32c3-builtin.cfg"] if using built-in usb jtag or ["board/esp32c3-ftdi.cfg"] if using ESP-PROG-JTAG. 
So apply this but still I face the same error please help bro.

**Comment by Ashutosh-017** [comment]
I connected following pins
GPIO19 with USB D+
GPIO18 with USB D-
5V to VCC
Ground to Ground 
Then,
I am facing this error 
[OpenOCD]
❌ Error: libusb_open() failed with LIBUSB_
[OpenOCD]
❌ ERROR_NOT_SUPPORTED
Error: libusb_open() failed with LIBUSB_ERROR_NOT_FOUND
Error: esp_usb_jtag: could not find or open device!
Please provide support
