### ISSUE TITLE
Debug Adapter errors  "Arduino as component" extension template projects.

### ISSUE THREAD

**Issue by yizakat** [espressif/vscode-esp-idf-extension#1065]
### OS

Windows

### Operating System version

11

### Visual Studio Code version

1.83.1

### ESP-IDF version

5.1.1

### Python version

3.11.6

### Doctor command output

Happy to provide this but I don't think it will add to the context. 

### Extension

This file is not present.

### Description

I am unable to start debugging (using the default ESP launch configuration) for a project generated from the extension template "**Arduino as Component**".

Note: My ESP debugging setup **works as expected on other ESP projects and examples**.  Generally, I can debug with either the ESP or GDB launch configurations with minimal problems.

### Debug Message

```plain
[OpenOCD]
Info : dropped 'gdb' connection

[Debug Adapter]
Exception in thread Thread-1 (_readerthread):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner

[Debug Adapter]
Exception in thread Thread-2 (_readerthread):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "subprocess.py", line 1552, in _readerthread

[Debug Adapter]
OSError: [Errno 22] Invalid argument
  File "threading.py", line 975, in run
  File "subprocess.py", line 1552, in _readerthread
OSError: [Errno 22] Invalid argument

[Debug Adapter]
DEBUG_ADAPTER_STOPPED
2023-10-22 12:50:39,846 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_STOPPED
```

### Other Steps to Reproduce

Note: I have no problem debugging other projects, those that are created from examples or by hand.  This seems specific to this particular template-generated code.

I have tried both the ESP launch and GDB launch and neither works, both work correctly for all other projects.

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by yizakat** [comment]
Reviewing my comments, I'm not sure if this is a problem with debugging or with the template in general, it looks to me as though this is an error in the actual bootloader and the debugger is just reporting that it can't start debugging because it can't start the process.

**Comment by yizakat** [comment]
OK - no idea why but this suddenly went away on all projects.  I had just finished comparing a simple blink project and the generated template using a logic analyser (both of which worked) - and for some reasons so does the debugger.  So will close this.

![image](https://github.com/espressif/vscode-esp-idf-extension/assets/53142686/da1805c1-1f1d-4946-838a-19af505174c1)
