### ISSUE TITLE
[Bug Report]: FileNotFoundError, when installing IDF Onboarding Tools (VSC-520)

### ISSUE THREAD

**Issue by xZise** [espressif/vscode-esp-idf-extension#260]
**Describe the bug**
While configuring the IDF Onboarding plugin it cannot install the tools correctly.

**To Reproduce**
Installed the extension, started the configuration and got stuck in "ESP-IDF Tools":

```
idf_versions.txt has (1) KB
idf_versions.txt progress: 100.00% (0.08 / 0.08) KB
idf_versions.txt has (1) KB
idf_versions.txt progress: 100.00% (0.08 / 0.08) KB
Saving C:\Users\Fabian\AppData\Local\Programs\Python\Python36\python.exe to create python virtual environment.

Downloading Toolchain for Xtensa (ESP32) based on GCC
Found xtensa-esp32-elf in C:\Users\Fabian\.espressif\dist
Downloading Toolchain for Xtensa (ESP32-S2) based on GCC
Found xtensa-esp32s2-elf in C:\Users\Fabian\.espressif\dist
Downloading Toolchain for ESP32 ULP coprocessor
Found esp32ulp-elf in C:\Users\Fabian\.espressif\dist
Downloading Toolchain for ESP32-S2 ULP coprocessor
Found esp32s2ulp-elf in C:\Users\Fabian\.espressif\dist
Downloading CMake build system
Found cmake in C:\Users\Fabian\.espressif\dist
Downloading OpenOCD for ESP32
Found openocd-esp32 in C:\Users\Fabian\.espressif\dist
Downloading Ninja build system
Found ninja in C:\Users\Fabian\.espressif\dist
Downloading IDF wrapper tool for Windows
Found idf-exe in C:\Users\Fabian\.espressif\dist
Downloading Ccache (compiler cache)
Found ccache in C:\Users\Fabian\.espressif\dist

Installing package Toolchain for Xtensa (ESP32) based on GCC
Installing zip package Toolchain for Xtensa (ESP32) based on GCC
Installing package Toolchain for Xtensa (ESP32-S2) based on GCC
Installing zip package Toolchain for Xtensa (ESP32-S2) based on GCC
Installing package Toolchain for ESP32 ULP coprocessor
Installing zip package Toolchain for ESP32 ULP coprocessor
Installing package Toolchain for ESP32-S2 ULP coprocessor
Installing zip package Toolchain for ESP32-S2 ULP coprocessor
Installing package CMake build system
Installing zip package CMake build system
Installing package OpenOCD for ESP32
Installing zip package OpenOCD for ESP32
Installing package Ninja build system
Installing zip package Ninja build system
Installing package IDF wrapper tool for Windows
Installing zip package IDF wrapper tool for Windows
Installing package Ccache (compiler cache)
Installing zip package Ccache (compiler cache)
Installing python virtualenv and ESP-IDF python requirements...
Creating a new Python environment in C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env ...



Collecting wheel
  Using cached https://files.pythonhosted.org/packages/65/63/39d04c74222770ed1589c0eaba06c05891801219272420b40311cd60c880/wheel-0.36.2-py2.py3-none-any.whl
Installing collected packages: wheel
Successfully installed wheel-0.36.2
You are using pip version 9.0.1, however version 20.3.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Collecting wheel
  Using cached https://files.pythonhosted.org/packages/65/63/39d04c74222770ed1589c0eaba06c05891801219272420b40311cd60c880/wheel-0.36.2-py2.py3-none-any.whl
Installing collected packages: wheel
Successfully installed wheel-0.36.2
You are using pip version 9.0.1, however version 20.3.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


Processing \\${idf_path}\tools\kconfig_new\esp-windows-curses
Exception:
Traceback (most recent call last):
  File "C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env\lib\site-packages\pip\download.py", line 809, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env\lib\site-packages\pip\download.py", line 715, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env\lib\site-packages\pip\utils\__init__.py", line 602, in unpack_file
    tarfile.is_tarfile(filename) or
  File "C:\Users\Fabian\AppData\Local\Programs\Python\Python36\lib\tarfile.py", line 2447, in is_tarfile
    t = open(name)
  File "C:\Users\Fabian\AppData\Local\Programs\Python\Python36\lib\tarfile.py", line 1568, in open
    return func(name, "r", fileobj, **kwargs)
  File "C:\Users\Fabian\AppData\Local\Programs\Python\Python36\lib\tarfile.py", line 1633, in gzopen
    fileobj = gzip.GzipFile(name, mode + "b", compresslevel, fileobj)
  File "C:\Users\Fabian\AppData\Local\Programs\Python\Python36\lib\gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '\\\\${IDF_PATH}\\tools\\kconfig_new\\esp-windows-curses'
You are using pip version 9.0.1, however version 20.3.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Command failed: "C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env\Scripts\python.exe" -m pip install -r "g:\Programme\esp-idf\requirements.txt"
Exception:
Traceback (most recent call last):
  File "C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env\lib\site-packages\pip\download.py", line 809, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env\lib\site-packages\pip\download.py", line 715, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env\lib\site-packages\pip\utils\__init__.py", line 602, in unpack_file
    tarfile.is_tarfile(filename) or
  File "C:\Users\Fabian\AppData\Local\Programs\Python\Python36\lib\tarfile.py", line 2447, in is_tarfile
    t = open(name)
  File "C:\Users\Fabian\AppData\Local\Programs\Python\Python36\lib\tarfile.py", line 1568, in open
    return func(name, "r", fileobj, **kwargs)
  File "C:\Users\Fabian\AppData\Local\Programs\Python\Python36\lib\tarfile.py", line 1633, in gzopen
    fileobj = gzip.GzipFile(name, mode + "b", compresslevel, fileobj)
  File "C:\Users\Fabian\AppData\Local\Programs\Python\Python36\lib\gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '\\\\${IDF_PATH}\\tools\\kconfig_new\\esp-windows-curses'
You are using pip version 9.0.1, however version 20.3.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Command failed: "C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env\Scripts\python.exe" -m pip install -r "g:\Programme\esp-idf\requirements.txt"
Exception:
Traceback (most recent call last):
  File "C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env\lib\site-packages\pip\download.py", line 809, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env\lib\site-packages\pip\download.py", line 715, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "C:\Users\Fabian\.espressif\python_env\idf4.1_py3.6_env\lib\site-packages\pip\utils\__init__.py", line 602, in unpack_file
    tarfile.is_tarfile(filename) or
  File "C:\Users\Fabian\AppData\Local\Programs\Python\Python36\lib\tarfile.py", line 2447, in is_tarfile
    t = open(name)
  File "C:\Users\Fabian\AppData\Local\Programs\Python\Python36\lib\tarfile.py", line 1568, in open
    return func(name, "r", fileobj, **kwargs)
  File "C:\Users\Fabian\AppData\Local\Programs\Python\Python36\lib\tarfile.py", line 1633, in gzopen
    fileobj = gzip.GzipFile(name, mode + "b", compresslevel, fileobj)
  File "C:\Users\Fabian\AppData\Local\Programs\Python\Python36\lib\gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '\\\\${IDF_PATH}\\tools\\kconfig_new\\esp-windows-curses'
You are using pip version 9.0.1, however version 20.3.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


The following paths should be added to env PATH
.;C:\Users\Fabian\AppData\Local\Programs\Python\Python36;C:\Users\Fabian\.espressif\tools\xtensa-esp32-elf\esp-2020r2-8.2.0\xtensa-esp32-elf\bin;C:\Users\Fabian\.espressif\tools\xtensa-esp32s2-elf\esp-2020r2-8.2.0\xtensa-esp32s2-elf\bin;C:\Users\Fabian\.espressif\tools\esp32ulp-elf\2.28.51-esp-20191205\esp32ulp-elf-binutils\bin;C:\Users\Fabian\.espressif\tools\esp32s2ulp-elf\2.28.51-esp-20191205\esp32s2ulp-elf-binutils\bin;C:\Users\Fabian\.espressif\tools\cmake\3.13.4\bin;C:\Users\Fabian\.espressif\tools\openocd-esp32\v0.10.0-esp32-20191114\openocd-esp32\bin;C:\Users\Fabian\.espressif\tools\ninja\1.9.0;C:\Users\Fabian\.espressif\tools\idf-exe\1.0.1;C:\Users\Fabian\.espressif\tools\ccache\3.7
```

**Expected behavior**
To complete? There is no indication on how to procede.

**Environment (please complete the following information):**

- OS Name & Version: Windows 10
- VSCode Version: 1.52.1
- ESP-IDF Version: 4.1
- Python Version: 3.6.4

**Logs**
[esp_idf_vsc_ext.log](https://github.com/espressif/vscode-esp-idf-extension/files/5760367/esp_idf_vsc_ext.log)

**Comment by brianignacio5** [comment]
Hey @xZise  have you tried again with the new setup wizard ? This error should be fixed in latest master version. I did test with ESP-IDF v4.1 and Python 3.7 on Windows 10 and it is working.
