### ISSUE TITLE
Tasks dont work... should they? (VSC-239)

### ISSUE THREAD

**Issue by mitchjs** [espressif/vscode-esp-idf-extension#34]
**Describe the bug**
run task build (none of them work, build, clean, flash)

**To Reproduce**
Terminal->Run Task... pick anything...

**Expected behavior**
it should build the project

**Screenshots**
![image](https://user-images.githubusercontent.com/747871/74402886-827f6480-4df3-11ea-87d7-a55a7d9c578a.png)

**Environment (please complete the following information):**
- OS Name & Version: Windows 10
- VSCode Version: 1.42
- ESP-IDF Version: v4.0
- Python Version: 3.7

**Additional context**
not sure why its trying to do anything with WINPTY_EXE...
this is NOT an MSYS2 environment!
MSYSTEM is not in os.environ

output of terminal:
`> Executing task: C:\Users\mitchjs\.espressif\python_env\idf4.0_py3.7_env\Scripts\python.exe C:\Users\mitchjs\esp-idf\tools\idf.py build <

Traceback (most recent call last):
  File "C:\Users\mitchjs\esp-idf\tools\idf.py", line 1298, in <module>
    [WINPTY_EXE, sys.executable] + sys.argv, env=os.environ
  File "C:\Users\mitchjs\AppData\Local\Programs\Python\Python37\Lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\mitchjs\AppData\Local\Programs\Python\Python37\Lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\mitchjs\AppData\Local\Programs\Python\Python37\Lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.`

**Comment by mitchjs** [comment]
got it in VCS user settings was


"terminal.integrated.env.windows": {
"CHERE_INVOKING": "1",
"MSYSTEM": "MINGW32",
},

removed that... and all good
was tricking python scripts that in MSYS environment
