### ISSUE TITLE
[Bug Report]: Debug Adapter (main) - ERROR - 'frame' (VSC-784)

### ISSUE THREAD

**Issue by stefaandesmet2003** [espressif/vscode-esp-idf-extension#570]
Hi, 
this vscode extension is great, but I'm having an issue to get debugging working with the 'espidf' launch type.
my setup is a 'Wemos' ESP32 devboard connected to a FT232H USB adapter for JTAG debugging.
the ESP-IDF Debug adapter plugin systematically raises an exception before it even connects to the running openocd server.
The extension shows a popup with no information except 'open launch.json' :

The espidf launch config is the default as per instruction
![Screenshot from 2021-11-08 18-04-18](https://user-images.githubusercontent.com/11933661/140786171-a7b825d0-cd4b-4e6d-895a-1b5c96bcfbb4.png)

The setup does work correctly with a cppdbg launch configuration. Both configurations are attached. (doctor.txt)
I had the issue with ESP-IDF4.3, now moved to master branch, but same result.
OpenOCD view shows a running openocd server that receives no command from the ESP-IDF Debug Adapter plugin.
Thanks in advance for helping out!
Stefaan

**Environment (please complete the following information):**

[doctor.txt](https://github.com/espressif/vscode-esp-idf-extension/files/7498765/doctor.txt)

--------------------------------------------------------------------------------------------------------------------------------------------
OpenOCD View:
--------------------------------------------------------------------------------------------------------------------------------------------

Open On-Chip Debugger  v0.10.0-esp32-20210902 (2021-09-02-09:38)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
debug_level: 2

adapter speed: 20000 kHz

Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : ftdi: if you experience problems at higher adapter clocks, try the command "ftdi_tdo_sample_edge falling"
Info : clock speed 20000 kHz
Info : JTAG tap: esp32.cpu0 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : JTAG tap: esp32.cpu1 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : esp32.cpu0: Target halted, PC=0x400D483F, debug_reason=00000001
Info : esp32.cpu1: Target halted, PC=0x400E550A, debug_reason=00000000
Info : Listening on port 3333 for gdb connections

--------------------------------------------------------------------------------------------------------------------------------------------
ESP-IDF Debug Adapter View:
--------------------------------------------------------------------------------------------------------------------------------------------

2021-11-08 17:53:28,127 - Debug Adapter (main) - DEBUG - START_TIME_2021_11_08_17-53-28
2021-11-08 17:53:28,128 - Debug Adapter (main) - DEBUG - Init errors:None
2021-11-08 17:53:28,128 - Debug Adapter (main) - INFO - Working directory: /home/stefaan
2021-11-08 17:53:28,129 - Debug Adapter (main) - INFO - Arguments: 
{   'app_flash_off': 65536,
    'board_type': None,
    'cmdfile': None,
    'core_file': (),
    'debug': 4,
    'developer_mode': 'none',
    'device_name': '',
    'elfpath': ('/home/stefaan/Documents/dev/esp32/blink/build/blink.elf',),
    'log_file': '/home/stefaan/Documents/dev/esp32/blink/debug.log',
    'log_mult_files': None,
    'log_no_debug_console': None,
    'oocd': 'openocd',
    'oocd_args': None,
    'oocd_ip': 'localhost',
    'oocd_mode': 'connect_to_instance',
    'oocd_scripts': None,
    'port': 43474,
    'postmortem': False,
    'tmo_scale_factor': 1,
    'toolchain_prefix': None}
DEBUG_ADAPTER_STARTED
2021-11-08 17:53:28,129 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_STARTED
2021-11-08 17:53:28,129 - Debug Adapter (main) - INFO - Starting. Cmd: /home/stefaan/.vscode/extensions/espressif.esp-idf-extension-1.2.0/esp_debug_adapter/debug_adapter_main.py -d 4 -e /home/stefaan/Documents/dev/esp32/blink/build/blink.elf -l /home/stefaan/Documents/dev/esp32/blink/debug.log -p 43474 -dn  -a 0x10000

2021-11-08 17:53:28,132 - Debug Adapter (main) - INFO - Listening on port 43474 (host: acer,local ip: 127.0.1.1)
DEBUG_ADAPTER_READY2CONNECT
2021-11-08 17:53:28,132 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_READY2CONNECT
2021-11-08 17:53:28,134 - Debug Adapter (main) - DEBUG - Got connection
2021-11-08 17:53:28,135 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Debug adapter -> Extension: DEBUG_ADAPTER_STARTED\n", "source": {}}, "seq": 0}

2021-11-08 17:53:28,137 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Starting. Cmd: /home/stefaan/.vscode/extensions/espressif.esp-idf-extension-1.2.0/esp_debug_adapter/debug_adapter_main.py -d 4 -e /home/stefaan/Documents/dev/esp32/blink/build/blink.elf -l /home/stefaan/Documents/dev/esp32/blink/debug.log -p 43474 -dn  -a 0x10000\n\n", "source": {}}, "seq": 1}

2021-11-08 17:53:28,139 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Listening on port 43474 (host: acer,local ip: 127.0.1.1)\n", "source": {}}, "seq": 2}

2021-11-08 17:53:28,140 - Debug Adapter (ReaderThread) - DEBUG - read line: >>b'Content-Length: 410\\r\\n'<<

2021-11-08 17:53:28,141 - Debug Adapter (ReaderThread) - DEBUG - read line: >>b'\\r\\n'<<

2021-11-08 17:53:28,141 - Debug Adapter(Command Processor) - DEBUG - Got json: {
    "arguments": {
        "adapterID": "espidf",
        "clientID": "vscode",
        "clientName": "Visual Studio Code",
        "columnsStartAt1": true,
        "linesStartAt1": true,
        "locale": "en-us",
        "pathFormat": "path",
        "supportsInvalidatedEvent": true,
        "supportsMemoryReferences": true,
        "supportsProgressReporting": true,
        "supportsRunInTerminalRequest": true,
        "supportsVariablePaging": true,
        "supportsVariableType": true
    },
    "command": "initialize",
    "seq": 1,
    "type": "request"
}
2021-11-08 17:53:28,143 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Debug adapter -> Extension: DEBUG_ADAPTER_READY2CONNECT\n", "source": {}}, "seq": 3}

2021-11-08 17:53:28,147 - Gdb - DEBUG - MI->: -gdb-set mi-async on
2021-11-08 17:53:28,150 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Got connection\n", "source": {}}, "seq": 4}

2021-11-08 17:53:28,151 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Got json: {\n    \"arguments\": {\n        \"adapterID\": \"espidf\",\n        \"clientID\": \"vscode\",\n        \"clientName\": \"Visual Studio Code\",\n        \"columnsStartAt1\": true,\n        \"linesStartAt1\": true,\n        \"locale\": \"en-us\",\n        \"pathFormat\": \"path\",\n        \"supportsInvalidatedEvent\": true,\n        \"supportsMemoryReferences\": true,\n        \"supportsProgressReporting\": true,\n        \"supportsRunInTerminalRequest\": true,\n        \"supportsVariablePaging\": true,\n        \"supportsVariableType\": true\n    },\n    \"command\": \"initialize\",\n    \"seq\": 1,\n    \"type\": \"request\"\n}\n", "source": {}}, "seq": 5}

2021-11-08 17:53:28,226 - Gdb - DEBUG - MI<-:
[{'message': 'thread-group-added',
  'payload': {'id': 'i1'},
  'stream': 'stdout',
  'token': None,
  'type': 'notify'},
 {'message': 'done',
  'payload': None,
  'stream': 'stdout',
  'token': None,
  'type': 'result'}]
2021-11-08 17:53:28,226 - Gdb - INFO - NOTIFY: thread-group-added {'id': 'i1'}
2021-11-08 17:53:28,226 - Gdb - DEBUG - RESULT: done None
2021-11-08 17:53:28,226 - Gdb - DEBUG - MI->: -gdb-set logging file /tmp/gdb_proc.log
2021-11-08 17:53:28,230 - Gdb - DEBUG - MI<-:
[{'message': 'done',
  'payload': None,
  'stream': 'stdout',
  'token': None,
  'type': 'result'}]
2021-11-08 17:53:28,230 - Gdb - DEBUG - RESULT: done None
2021-11-08 17:53:28,230 - Gdb - DEBUG - MI->: -gdb-set logging on
2021-11-08 17:53:28,234 - Gdb - DEBUG - MI<-:
[{'message': 'done',
  'payload': None,
  'stream': 'stdout',
  'token': None,
  'type': 'result'}]
2021-11-08 17:53:28,234 - Gdb - DEBUG - RESULT: done None
2021-11-08 17:53:28,234 - Debug Adapter (main) - DEBUG - Created gdb object of type: Gdb
2021-11-08 17:53:28,234 - Gdb - DEBUG - MI->: -file-exec-and-symbols /home/stefaan/Documents/dev/esp32/blink/build/blink.elf
2021-11-08 17:53:28,235 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Created gdb object of type: Gdb\n", "source": {}}, "seq": 6}

2021-11-08 17:53:28,272 - Gdb - DEBUG - MI<-:
[{'message': 'done',
  'payload': None,
  'stream': 'stdout',
  'token': None,
  'type': 'result'}]
2021-11-08 17:53:28,272 - Gdb - DEBUG - RESULT: done None
2021-11-08 17:53:28,273 - Gdb - DEBUG - Skipped connection to remote target
2021-11-08 17:53:28,273 - Debug Adapter(Command Processor) - DEBUG - Processed command: initialize
2021-11-08 17:53:28,273 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "response", "request_seq": 1, "success": true, "command": "initialize", "seq": 7, "body": {"supportsConfigurationDoneRequest": true, "supportsFunctionBreakpoints": false, "supportsConditionalBreakpoints": true, "supportsHitConditionalBreakpoints": true, "supportsEvaluateForHovers": false, "exceptionBreakpointFilters": false, "supportsStepBack": false, "supportsSetVariable": true, "supportsRestartFrame": false, "supportsGotoTargetsRequest": false, "supportsStepInTargetsRequest": true, "supportsCompletionsRequest": false, "completionTriggerCharacters": false, "supportsModulesRequest": false, "additionalModuleColumns": false, "supportedChecksumAlgorithms": false, "supportsRestartRequest": true, "supportsExceptionOptions": false, "supportsValueFormattingOptions": false, "supportsExceptionInfoRequest": false, "supportTerminateDebuggee": true, "supportsDelayedStackTraceLoading": false, "supportsLoadedSourcesRequest": false, "supportsLogPoints": false, "supportsTerminateThreadsRequest": false, "supportsSetExpression": false, "supportsTerminateRequest": false, "supportsDataBreakpoints": false, "supportsReadMemoryRequest": false, "supportsDisassembleRequest": false, "supportsCancelRequest": false, "supportsBreakpointLocationsRequest": false, "supportsClipboardContext": false, "supportsSteppingGranularity": false, "supportsInstructionBreakpoints": false}}

2021-11-08 17:53:28,274 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "initialized", "seq": 8}

2021-11-08 17:53:28,274 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Debug Adapter initialized\n", "source": {}}, "seq": 9}

2021-11-08 17:53:28,274 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Processed command: initialize\n", "source": {}}, "seq": 10}

2021-11-08 17:53:28,285 - Debug Adapter (ReaderThread) - DEBUG - read line: >>b'Content-Length: 305\\r\\n'<<

2021-11-08 17:53:28,285 - Debug Adapter (ReaderThread) - DEBUG - read line: >>b'\\r\\n'<<

2021-11-08 17:53:28,286 - Debug Adapter(Command Processor) - DEBUG - Got json: {
    "arguments": {
        "__configurationTarget": 5,
        "__sessionId": "7585d60b-b78c-48ae-8020-4b5b46924620",
        "elfFilePath": "/home/stefaan/Documents/dev/esp32/blink/build/blink.elf",
        "name": "TEST ESP32debug",
        "request": "launch",
        "skipVerifyAppBinBeforeDebug": true,
        "type": "espidf"
    },
    "command": "launch",
    "seq": 2,
    "type": "request"
}
2021-11-08 17:53:28,286 - Gdb - DEBUG - MI->: -exec-run --all --start
2021-11-08 17:53:28,286 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Got json: {\n    \"arguments\": {\n        \"__configurationTarget\": 5,\n        \"__sessionId\": \"7585d60b-b78c-48ae-8020-4b5b46924620\",\n        \"elfFilePath\": \"/home/stefaan/Documents/dev/esp32/blink/build/blink.elf\",\n        \"name\": \"TEST ESP32debug\",\n        \"request\": \"launch\",\n        \"skipVerifyAppBinBeforeDebug\": true,\n        \"type\": \"espidf\"\n    },\n    \"command\": \"launch\",\n    \"seq\": 2,\n    \"type\": \"request\"\n}\n", "source": {}}, "seq": 11}

2021-11-08 17:53:28,296 - Gdb - DEBUG - MI<-:
[{'message': None,
  'payload': 'Function \\"main\\" not defined.\\n',
  'stream': 'stdout',
  'type': 'log'},
 {'message': None,
  'payload': 'Make breakpoint pending on future shared library load? (y or '
             '[n]) [answered N; input not from terminal]\\n',
  'stream': 'stdout',
  'type': 'console'},
 {'message': 'thread-group-started',
  'payload': {'id': 'i1', 'pid': '62913'},
  'stream': 'stdout',
  'token': None,
  'type': 'notify'},
 {'message': 'thread-created',
  'payload': {'group-id': 'i1', 'id': '1'},
  'stream': 'stdout',
  'token': None,
  'type': 'notify'},
 {'message': None,
  'payload': 'Failed to read a valid object file image from memory.\\n',
  'stream': 'stdout',
  'type': 'log'},
 {'message': 'running',
  'payload': None,
  'stream': 'stdout',
  'token': None,
  'type': 'result'},
 {'message': 'running',
  'payload': {'thread-id': 'all'},
  'stream': 'stdout',
  'token': None,
  'type': 'notify'}]
2021-11-08 17:53:28,296 - Gdb - DEBUG - LOG: 'Function \\"main\\" not defined.\\n'
2021-11-08 17:53:28,296 - Gdb - INFO - CONS: ('Make breakpoint pending on future shared library load? (y or [n]) [answered '
 'N; input not from terminal]\\n')
2021-11-08 17:53:28,296 - Gdb - INFO - NOTIFY: thread-group-started {'id': 'i1', 'pid': '62913'}
2021-11-08 17:53:28,296 - Gdb - INFO - NOTIFY: thread-created {'group-id': 'i1', 'id': '1'}
2021-11-08 17:53:28,296 - Gdb - DEBUG - LOG: 'Failed to read a valid object file image from memory.\\n'
2021-11-08 17:53:28,297 - Gdb - DEBUG - RESULT: running None
2021-11-08 17:53:28,500 - Gdb - INFO - NOTIFY: running {'thread-id': 'all'}
2021-11-08 17:53:28,501 - Gdb - INFO - NOTIFY: thread-created {'group-id': 'i1', 'id': '2'}
2021-11-08 17:53:28,502 - Gdb - INFO - CONS: '[New LWP 62917]\\n'
2021-11-08 17:53:28,508 - Gdb - INFO - NOTIFY: running {'thread-id': '2'}
2021-11-08 17:53:28,509 - Gdb - INFO - CONS: '[LWP 62917 exited]\\n'
2021-11-08 17:53:28,510 - Gdb - INFO - NOTIFY: thread-exited {'group-id': 'i1', 'id': '2'}
2021-11-08 17:53:28,510 - Gdb - INFO - CONS: '[Inferior 1 (process 62913) exited with code 0377]\\n'
2021-11-08 17:53:28,511 - Gdb - INFO - NOTIFY: thread-exited {'group-id': 'i1', 'id': '1'}
2021-11-08 17:53:28,511 - Gdb - INFO - NOTIFY: thread-group-exited {'exit-code': '0377', 'id': 'i1'}
2021-11-08 17:53:28,512 - Gdb - INFO - NOTIFY: stopped {'exit-code': '0377', 'reason': 'exited'}
2021-11-08 17:53:28,514 - Debug Adapter (main) - ERROR - 'frame'
Traceback (most recent call last):
  File "/home/stefaan/.vscode/extensions/espressif.esp-idf-extension-1.2.0/esp_debug_adapter/debug_adapter/command_processor.py", line 143, in on_launch_request
    self.da.run(start=(not self.da.state.no_debug))
  File "/home/stefaan/.vscode/extensions/espressif.esp-idf-extension-1.2.0/esp_debug_adapter/debug_adapter/debug_adapter.py", line 736, in run
    rsn = self._gdb.wait_target_state(dbg.TARGET_STATE_STOPPED, 10)
  File "/home/stefaan/.vscode/extensions/espressif.esp-idf-extension-1.2.0/esp_debug_adapter/debug_adapter/debug_backend/debug_backend/gdb.py", line 511, in wait_target_state
    self._parse_mi_resp(recs, state)
  File "/home/stefaan/.vscode/extensions/espressif.esp-idf-extension-1.2.0/esp_debug_adapter/debug_adapter/debug_backend/debug_backend/gdb.py", line 124, in _parse_mi_resp
    self._on_notify(rec)
  File "/home/stefaan/.vscode/extensions/espressif.esp-idf-extension-1.2.0/esp_debug_adapter/debug_adapter/debug_backend/debug_backend/gdb.py", line 71, in _on_notify
    self._curr_frame = rec['payload']['frame']
KeyError: 'frame'
2021-11-08 17:53:28,520 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "'frame'\n", "source": {}}, "seq": 12}

2021-11-08 17:53:28,535 - Debug Adapter(Command Processor) - DEBUG - Processed command: launch
2021-11-08 17:53:28,536 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "'frame'\n", "source": {}}, "seq": 13}

2021-11-08 17:53:28,537 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "response", "request_seq": 2, "success": false, "command": "launch", "seq": 14}

2021-11-08 17:53:28,538 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Debug Adapter is not running\n", "source": {}}, "seq": 15}

2021-11-08 17:53:28,538 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Processed command: launch\n", "source": {}}, "seq": 16}

2021-11-08 17:53:28,539 - Debug Adapter (ReaderThread) - DEBUG - read line: >>b'Content-Length: 56\\r\\n'<<

2021-11-08 17:53:28,539 - Debug Adapter (ReaderThread) - DEBUG - read line: >>b'\\r\\n'<<

2021-11-08 17:53:28,540 - Debug Adapter(Command Processor) - DEBUG - Got json: {
    "arguments": {},
    "command": "configurationDone",
    "seq": 3,
    "type": "request"
}
2021-11-08 17:53:28,540 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Got json: {\n    \"arguments\": {},\n    \"command\": \"configurationDone\",\n    \"seq\": 3,\n    \"type\": \"request\"\n}\n", "source": {}}, "seq": 17}

2021-11-08 17:53:28,541 - Debug Adapter(Command Processor) - DEBUG - Processed command: configurationDone
2021-11-08 17:53:28,541 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "response", "request_seq": 3, "success": true, "command": "configurationDone", "seq": 18}

2021-11-08 17:53:28,542 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Processed command: configurationDone\n", "source": {}}, "seq": 19}

2021-11-08 17:53:28,594 - Debug Adapter (ReaderThread) - DEBUG - read line: >>b'Content-Length: 79\\r\\n'<<

2021-11-08 17:53:28,595 - Debug Adapter (ReaderThread) - DEBUG - read line: >>b'\\r\\n'<<

2021-11-08 17:53:28,595 - Debug Adapter(Command Processor) - DEBUG - Got json: {
    "arguments": {
        "restart": false
    },
    "command": "disconnect",
    "seq": 4,
    "type": "request"
}
2021-11-08 17:53:28,595 - Debug Adapter (main) - DEBUG - Adapter is Stopping...
2021-11-08 17:53:28,595 - Debug Adapter (main) - DEBUG - Stopping target poller
2021-11-08 17:53:28,596 - Debug Adapter (main) - DEBUG - Closing the GDB process
2021-11-08 17:53:28,596 - Gdb - DEBUG - MI->: -gdb-exit
2021-11-08 17:53:28,596 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Got json: {\n    \"arguments\": {\n        \"restart\": false\n    },\n    \"command\": \"disconnect\",\n    \"seq\": 4,\n    \"type\": \"request\"\n}\n", "source": {}}, "seq": 20}

2021-11-08 17:53:28,596 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Debug Adapter stopped\n", "source": {}}, "seq": 21}

2021-11-08 17:53:28,596 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Adapter is Stopping...\n", "source": {}}, "seq": 22}

2021-11-08 17:53:28,597 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Stopping target poller\n", "source": {}}, "seq": 23}

2021-11-08 17:53:28,597 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Closing the GDB process\n", "source": {}}, "seq": 24}

2021-11-08 17:53:33,596 - Debug Adapter (main) - DEBUG - Failed to wait for GDB/MI to become ready!
2021-11-08 17:53:33,600 - Debug Adapter (main) - DEBUG - Closing the Socket
2021-11-08 17:53:33,601 - Debug Adapter (main) - DEBUG - Stopping of the Writer thread
2021-11-08 17:53:33,602 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Failed to wait for GDB/MI to become ready!\n", "source": {}}, "seq": 25}

2021-11-08 17:53:33,609 - Debug Adapter (main) - DEBUG - Stopping of the Reader thread
2021-11-08 17:53:33,609 - Debug Adapter (main) - DEBUG - Adapter is Stopped
DEBUG_ADAPTER_STOPPED
2021-11-08 17:53:33,610 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_STOPPED
2021-11-08 17:53:33,614 - Debug Adapter(Command Processor) - DEBUG - Processed command: disconnect
[Stopped] : ESP-IDF Debug Adapter

**Logs**
If applicable, please share the log file which can be obtained from

- Windows: `%USERPROFILE%\.vscode\extensions\espressif.esp-idf-extension-VERSION\esp_idf_vsc_ext.log`
- Linux & MacOSX: `$HOME/.vscode/extensions/espressif.esp-idf-extension-VERSION/esp_idf_vsc_ext.log`

**Extension Configuration settings**
Open Command Palette (F1 or View Menu -> Command Palette) and type `Preferences: Open Settings (JSON)` or use `{CURRENT_PROJECT}/.vscode/settings.json` to get the following extension configuration settings value:

- `idf.espIdfPath` (MacOS or Linux) or `idf.espIdfPathWin` (Windows) also called `Path to locate ESP-IDF framework (IDF_PATH)` in `Preferences: Open Settings (UI)`.
- `idf.pythonBinPath` (MacOS or Linux) or `idf.pythonBinPathWin` (Windows) also called `Python absolute binary path used to execute ESP-IDF Python Scripts` in `Preferences: Open Settings (UI)`.
- `idf.openOcdConfigs` also called `List of configuration files inside OpenOCD Scripts directory` in `Preferences: Open Settings (UI)`.
- `idf.customExtraPaths` also called `Paths to be appended to PATH` in `Preferences: Open Settings (UI)`.
- `idf.customExtraVars` also called `Variables to be added to system environment variables` in `Preferences: Open Settings (UI)`.
- `idf.adapterTargetName` also called `Target name for ESP-IDF Debug Adapter` in `Preferences: Open Settings (UI)`.
- `idf.customAdapterTargetName` is used when `idf.adapterTargetName` is set to `custom`.

**Additional context**

**Comment by stefaandesmet2003** [comment]
Hi, 
apparently device name , wasn't set; must have missed that somehow. corrected now to "idf.adapterTargetName": "esp32" in settings.json
And problem looks mostly solved.
Sorry to spam this repo :/

**Comment by brianignacio5** [comment]
I'm glad you had it fixed! 

Let us know if there something we can help with 😄
