### ISSUE TITLE
[Bug Report]: cannot start debug session with internal USB/JTAG adapter

### ISSUE THREAD

**Issue by ScarsFun** [espressif/vscode-esp-idf-extension#727]
Hello I've a problem starting debug session with ESP32C3 with internal USB/JTAG adapter. Flashing with internal adapter works well. I can start a manual gdb session correctly. problem seem to be the esp debug adapter in vscode extension.
I tryed to start manually the debug adapter extension with this error. I'm not a pyton expert so I cannot find the solution.

thanks in advance.

```
PS C:\Users\MAX\WORK\esp32\blink> python C:\Users\MAX\.vscode\extensions\espressif.esp-idf-extension-1.4.0\esp_debug_adapter\debug_adapter_main.py -e blink.elf -ip localhost -dn esp32c3 -d 5 -ln
2022-06-01 15:16:51,906 - Debug Adapter (main) - DEBUG - START_TIME_2022_06_01_15-16-51
2022-06-01 15:16:51,907 - Debug Adapter (main) - DEBUG - Init errors:None
2022-06-01 15:16:51,907 - Debug Adapter (main) - INFO - Working directory: C:\Users\MAX\WORK\esp32\blink
2022-06-01 15:16:51,908 - Debug Adapter (main) - INFO - Arguments:
{   'app_flash_off': 65536,
    'board_type': None,
    'cmdfile': None,
    'core_file': (),
    'debug': 5,
    'developer_mode': 'none',
    'device_name': 'esp32c3',
    'elfpath': ('blink.elf',),
    'log_file': None,
    'log_mult_files': None,
    'log_no_debug_console': True,
    'oocd': 'openocd',
    'oocd_args': None,
    'oocd_ip': 'localhost',
    'oocd_mode': 'connect_to_instance',
    'oocd_scripts': None,
    'port': 43474,
    'postmortem': False,
    'tmo_scale_factor': 1,
    'toolchain_prefix': None}
Traceback (most recent call last):
  File "C:\Users\MAX\.vscode\extensions\espressif.esp-idf-extension-1.4.0\esp_debug_adapter\debug_adapter_main.py", line 30, in <module>
    cli(sys.argv[1:])
  File "C:\Users\MAX\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\MAX\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\MAX\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\MAX\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\MAX\AppData\Local\Programs\Python\Python310\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\MAX\.vscode\extensions\espressif.esp-idf-extension-1.4.0\esp_debug_adapter\debug_adapter\cli.py", line 145, in cli
    dbg_a = DebugAdapter(args=args_main)
  File "C:\Users\MAX\.vscode\extensions\espressif.esp-idf-extension-1.4.0\esp_debug_adapter\debug_adapter\debug_adapter.py", line 76, in __init__
    _, self.target_triple = os.path.split(args.toolchain_prefix)
  File "C:\Users\MAX\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 185, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
PS C:\Users\MAX\WORK\esp32\blink>
```
**ESP-IDF doctor**
```
---------------------------------------------- ESP-IDF Extension for Visual Studio Code report ---------------------------------------------
OS win32 x64 10.0.22000 
System environment variable IDF_PYTHON_ENV_PATH 
 undefined 
System environment variable PATH 
 C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2021.10\bin;C:\Users\MAX\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\MAX\AppData\Local\Programs\Python\Python310\;C:\Users\MAX\AppData\Local\Microsoft\WindowsApps; 
System environment variable PYTHON 
 undefined 
Visual Studio Code version 1.67.2 
Visual Studio Code language en 
Visual Studio Code shell C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe 
ESP-IDF Extension version 1.4.0 
---------------------------------------------------- Extension configuration settings ------------------------------------------------------
ESP-ADF Path (idf.espAdfPath) ${env:ADF_PATH}
ESP-IDF Path (idf.espIdfPath) C:\Users\MAX\esp\esp-idf
ESP-MDF Path (idf.espMdfPath) ${env:MDF_PATH}
Custom extra paths (idf.customExtraPaths) C:\Users\MAX\.espressif\tools\xtensa-esp32-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32-elf\bin;C:\Users\MAX\.espressif\tools\xtensa-esp32s2-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32s2-elf\bin;C:\Users\MAX\.espressif\tools\xtensa-esp32s3-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32s3-elf\bin;C:\Users\MAX\.espressif\tools\riscv32-esp-elf\esp-2021r2-patch3-8.4.0\riscv32-esp-elf\bin;C:\Users\MAX\.espressif\tools\esp32ulp-elf\2.28.51-esp-20191205\esp32ulp-elf-binutils\bin;C:\Users\MAX\.espressif\tools\esp32s2ulp-elf\2.28.51-esp-20191205\esp32s2ulp-elf-binutils\bin;C:\Users\MAX\.espressif\tools\cmake\3.20.3\bin;C:\Users\MAX\.espressif\tools\openocd-esp32\v0.11.0-esp32-20211220\openocd-esp32\bin;C:\Users\MAX\.espressif\tools\ninja\1.10.2;C:\Users\MAX\.espressif\tools\idf-exe\1.0.3;C:\Users\MAX\.espressif\tools\ccache\4.3\ccache-4.3-windows-64;C:\Users\MAX\.espressif\tools\dfu-util\0.9\dfu-util-0.9-win64
Custom extra vars (idf.customExtraVars) {"OPENOCD_SCRIPTS":"C:\\Users\\MAX\\.espressif\\tools\\openocd-esp32\\v0.11.0-esp32-20211220/openocd-esp32/share/openocd/scripts","IDF_CCACHE_ENABLE":"1"}
Virtual env Python Path (idf.pythonBinPath) C:\Users\MAX\.espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe
Serial port (idf.port) COM5
OpenOCD Configs (idf.openOcdConfigs) board/esp32c3-builtin.cfg
ESP-IDF Tools Path (idf.toolsPath) C:\Users\MAX\.espressif
Git Path (idf.gitPath) C:\Users\MAX\.espressif\tools\idf-git\2.30.1\cmd\git.exe
-------------------------------------------------------- Configurations access -------------------------------------------------------------
Access to ESP-ADF Path (idf.espAdfPath) false
Access to ESP-IDF Path (idf.espIdfPath) true
Access to ESP-MDF Path (idf.espMdfPath) false
Access to ESP-IDF Custom extra paths
Access to C:\Users\MAX\.espressif\tools\xtensa-esp32-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32-elf\bin: true
Access to C:\Users\MAX\.espressif\tools\xtensa-esp32s2-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32s2-elf\bin: true
Access to C:\Users\MAX\.espressif\tools\xtensa-esp32s3-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32s3-elf\bin: true
Access to C:\Users\MAX\.espressif\tools\riscv32-esp-elf\esp-2021r2-patch3-8.4.0\riscv32-esp-elf\bin: true
Access to C:\Users\MAX\.espressif\tools\esp32ulp-elf\2.28.51-esp-20191205\esp32ulp-elf-binutils\bin: true
Access to C:\Users\MAX\.espressif\tools\esp32s2ulp-elf\2.28.51-esp-20191205\esp32s2ulp-elf-binutils\bin: true
Access to C:\Users\MAX\.espressif\tools\cmake\3.20.3\bin: true
Access to C:\Users\MAX\.espressif\tools\openocd-esp32\v0.11.0-esp32-20211220\openocd-esp32\bin: true
Access to C:\Users\MAX\.espressif\tools\ninja\1.10.2: true
Access to C:\Users\MAX\.espressif\tools\idf-exe\1.0.3: true
Access to C:\Users\MAX\.espressif\tools\ccache\4.3\ccache-4.3-windows-64: true
Access to C:\Users\MAX\.espressif\tools\dfu-util\0.9\dfu-util-0.9-win64: true
Access to Virtual env Python Path (idf.pythonBinPath) true
Access to CMake in environment PATH undefined
Access to Ninja in environment PATH undefined
Access to ESP-IDF Tools Path (idf.toolsPath) true
----------------------------------------------------------- Executables Versions -----------------------------------------------------------
Git version 2.30.1.windows.1
ESP-IDF version 4.4.1
Python version 3.8.7
Python's pip version 20.3.3
-------------------------------------------------- Python packages in idf.pythonBinPath ----------------------------------------------------
bitstring version: 3.1.9
Brotli version: 1.0.9
certifi version: 2022.5.18.1
cffi version: 1.15.0
charset-normalizer version: 2.0.12
click version: 8.1.3
colorama version: 0.4.4
construct version: 2.10.54
contextlib2 version: 21.6.0
cryptography version: 37.0.2
ecdsa version: 0.17.0
esp-windows-curses version: 0.1
Flask version: 0.12.5
Flask-Compress version: 1.12
Flask-SocketIO version: 2.9.6
future version: 0.18.2
gcovr version: 5.1
gdbgui version: 0.13.2.0
gevent version: 1.5.0
greenlet version: 1.1.2
idf-component-manager version: 1.1.0
idna version: 3.3
itsdangerous version: 2.0.1
Jinja2 version: 3.0.3
kconfiglib version: 13.7.1
lxml version: 4.8.0
MarkupSafe version: 2.1.1
pip version: 20.3.3
psutil version: 5.9.1
pycparser version: 2.21
pyelftools version: 0.28
pygdbmi version: 0.9.0.2
Pygments version: 2.12.0
pyparsing version: 2.3.1
pyserial version: 3.5
python-engineio version: 3.14.2
python-socketio version: 4.6.1
pywin32 version: 304
PyYAML version: 6.0
reedsolo version: 1.5.4
requests version: 2.27.1
requests-toolbelt version: 0.9.1
schema version: 0.7.5
setuptools version: 62.3.2
six version: 1.16.0
tqdm version: 4.64.0
urllib3 version: 1.26.9
websocket-client version: 1.3.2
Werkzeug version: 0.16.1
wheel version: 0.36.2
windows-curses version: 2.3.0
xmlrunner version: 1.7.7
---------------------------------------------------- Check ESP-IDF python requirements.txt -------------------------------------------------
Check ESP-IDF Python packages Python requirements from C:\Users\MAX\esp\esp-idf\requirements.txt are satisfied.
---------------------------------------------------- Check extension requirements.txt ------------------------------------------------------
Check Extension Python packages Python requirements from c:\Users\MAX\.vscode\extensions\espressif.esp-idf-extension-1.4.0\requirements.txt are satisfied.
---------------------------------------------------- Check ESP-IDF debug adapter requirements.txt ------------------------------------------
Check Debug AdapterPython packages Python requirements from c:\Users\MAX\.vscode\extensions\espressif.esp-idf-extension-1.4.0\esp_debug_adapter\requirements.txt are satisfied.
---------------------------------------------------- Visual Studio Code launch.json --------------------------------------------------------
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "espidf",
      "name": "Launch",
      "request": "launch",
      "logLevel": 5
    }
  ]
} 
---------------------------------------------------- Visual Studio Code c_cpp_properties.json ----------------------------------------------
{
    "configurations": [
        {
            "name": "ESP-IDF",
            "compilerPath": "C:\\Users\\MAX\\.espressif\\tools\\riscv32-esp-elf\\esp-2021r2-patch3-8.4.0\\riscv32-esp-elf\\bin\\riscv32-esp-elf-gcc.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "includePath": [
                "${config:idf.espIdfPath}/components/**",
                "${config:idf.espIdfPathWin}/components/**",
                "${config:idf.espAdfPath}/components/**",
                "${config:idf.espAdfPathWin}/components/**",
                "${workspaceFolder}/**"
            ],
            "browse": {
                "path": [
                    "${config:idf.espIdfPath}/components",
                    "${config:idf.espIdfPathWin}/components",
                    "${config:idf.espAdfPath}/components/**",
                    "${config:idf.espAdfPathWin}/components/**",
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": false
            }
        }
    ],
    "version": 4
}
 
--------------------------------------------------------------------------------------------------------------------------------------------
```

this is output starting debug session (F5)

**open ocd** 
```
Open On-Chip Debugger  v0.11.0-esp32-20211220 (2021-12-20-15:43)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
debug_level: 2

Info : only one transport option; autoselect 'jtag'
Info : esp_usb_jtag: VID set to 0x303a and PID to 0x1001
Info : esp_usb_jtag: capabilities descriptor set to 0x2000
Warn : Transport "jtag" was already selected
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
❌ Error: libusb_open() failed with LIBUSB_ERROR_NOT_SUPPORTED
Info : esp_usb_jtag: Device found. Base speed 40000KHz, div range 1 to 255
Info : clock speed 40000 kHz
Info : JTAG tap: esp32c3.cpu tap/device found: 0x00005c25 (mfg: 0x612 (Espressif Systems), part: 0x0005, ver: 0x0)
Info : Examined RISC-V core; found 1 harts
Info :  hart 0: XLEN=32, misa=0x40101104
Info : starting gdb server for esp32c3 on 3333
Info : Listening on port 3333 for gdb connections
Info : accepting 'gdb' connection on tcp/3333
Warn : No symbols for FreeRTOS!
Info : [0] Found 8 triggers
Info : Flash mapping 0: 0x10020 -> 0x3c020020, 31 KB
Info : Flash mapping 1: 0x20020 -> 0x42000020, 81 KB
Info : Auto-detected flash bank 'esp32c3.flash' size 4096 KB
Info : Using flash bank 'esp32c3.flash' size 4096 KB
Info : Flash mapping 0: 0x10020 -> 0x3c020020, 31 KB
Info : Flash mapping 1: 0x20020 -> 0x42000020, 81 KB
Info : Using flash bank 'esp32c3.irom' size 84 KB
Info : Flash mapping 0: 0x10020 -> 0x3c020020, 31 KB
Info : Flash mapping 1: 0x20020 -> 0x42000020, 81 KB
Info : Using flash bank 'esp32c3.drom' size 32 KB
Info : dropped 'gdb' connection
```

**esp-idf debug adapter**

```
2022-06-01 15:15:52,705 - Debug Adapter (main) - DEBUG - START_TIME_2022_06_01_15-15-52
2022-06-01 15:15:52,705 - Debug Adapter (main) - DEBUG - Init errors:None
2022-06-01 15:15:52,705 - Debug Adapter (main) - INFO - Working directory: C:\Program Files\Microsoft VS Code
2022-06-01 15:15:52,706 - Debug Adapter (main) - INFO - Arguments: 
{   'app_flash_off': 65536,
    'board_type': None,
    'cmdfile': None,
    'core_file': (),
    'debug': 5,
    'developer_mode': 'none',
    'device_name': 'esp32c3',
    'elfpath': ('c:\\Users\\MAX\\WORK\\esp32\\blink\\build\\blink.elf',),
    'log_file': 'c:\\Users\\MAX\\WORK\\esp32\\blink\\debug.log',
    'log_mult_files': None,
    'log_no_debug_console': None,
    'oocd': 'openocd',
    'oocd_args': None,
    'oocd_ip': 'localhost',
    'oocd_mode': 'connect_to_instance',
    'oocd_scripts': None,
    'port': 43474,
    'postmortem': False,
    'tmo_scale_factor': 1,
    'toolchain_prefix': 'riscv32-esp-elf-'}
DEBUG_ADAPTER_STARTED
2022-06-01 15:15:52,706 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_STARTED
2022-06-01 15:15:52,707 - Debug Adapter (main) - INFO - Starting. Cmd: c:\Users\MAX\.vscode\extensions\espressif.esp-idf-extension-1.4.0\esp_debug_adapter\debug_adapter_main.py -d 5 -e c:\Users\MAX\WORK\esp32\blink\build\blink.elf -l c:\Users\MAX\WORK\esp32\blink\debug.log -p 43474 -dn esp32c3 -a 0x10000 -t riscv32-esp-elf-

2022-06-01 15:15:52,718 - Debug Adapter (main) - INFO - Listening on port 43474
DEBUG_ADAPTER_READY2CONNECT
2022-06-01 15:15:52,718 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_READY2CONNECT
2022-06-01 15:15:52,725 - Debug Adapter (main) - DEBUG - Got connection
2022-06-01 15:15:52,726 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Debug adapter -> Extension: DEBUG_ADAPTER_STARTED\n", "source": {}}, "seq": 0}

2022-06-01 15:15:52,727 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Starting. Cmd: c:\\Users\\MAX\\.vscode\\extensions\\espressif.esp-idf-extension-1.4.0\\esp_debug_adapter\\debug_adapter_main.py -d 5 -e c:\\Users\\MAX\\WORK\\esp32\\blink\\build\\blink.elf -l c:\\Users\\MAX\\WORK\\esp32\\blink\\debug.log -p 43474 -dn esp32c3 -a 0x10000 -t riscv32-esp-elf-\n\n", "source": {}}, "seq": 1}

2022-06-01 15:15:52,727 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Listening on port 43474\n", "source": {}}, "seq": 2}

2022-06-01 15:15:52,727 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Debug adapter -> Extension: DEBUG_ADAPTER_READY2CONNECT\n", "source": {}}, "seq": 3}

2022-06-01 15:15:52,728 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Got connection\n", "source": {}}, "seq": 4}

2022-06-01 15:15:52,743 - Debug Adapter (ReaderThread) - DEBUG - read line: >>b'Content-Length: 410\\r\\n'<<

2022-06-01 15:15:52,744 - Debug Adapter (ReaderThread) - DEBUG - read line: >>b'\\r\\n'<<

2022-06-01 15:15:52,744 - Debug Adapter(Command Processor) - DEBUG - Got json: {
    "arguments": {
        "adapterID": "espidf",
        "clientID": "vscode",
        "clientName": "Visual Studio Code",
        "columnsStartAt1": true,
        "linesStartAt1": true,
        "locale": "en-gb",
        "pathFormat": "path",
        "supportsInvalidatedEvent": true,
        "supportsMemoryReferences": true,
        "supportsProgressReporting": true,
        "supportsRunInTerminalRequest": true,
        "supportsVariablePaging": true,
        "supportsVariableType": true
    },
    "command": "initialize",
    "seq": 1,
    "type": "request"
}
2022-06-01 15:15:52,744 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Got json: {\n    \"arguments\": {\n        \"adapterID\": \"espidf\",\n        \"clientID\": \"vscode\",\n        \"clientName\": \"Visual Studio Code\",\n        \"columnsStartAt1\": true,\n        \"linesStartAt1\": true,\n        \"locale\": \"en-gb\",\n        \"pathFormat\": \"path\",\n        \"supportsInvalidatedEvent\": true,\n        \"supportsMemoryReferences\": true,\n        \"supportsProgressReporting\": true,\n        \"supportsRunInTerminalRequest\": true,\n        \"supportsVariablePaging\": true,\n        \"supportsVariableType\": true\n    },\n    \"command\": \"initialize\",\n    \"seq\": 1,\n    \"type\": \"request\"\n}\n", "source": {}}, "seq": 5}

2022-06-01 15:15:52,755 - Gdb - DEBUG - MI->: -gdb-set mi-async on
2022-06-01 15:15:52,800 - Gdb - DEBUG - MI<-:
[{'message': None,
  'payload': 'C:\\Users\\MAX\\.espressif\\tools\\riscv32-esp-elf\\esp-2021r2-patch3-8.4.0\\riscv32-esp-elf\\bin\\riscv32-esp-elf-gdb.exe: '
             "warning: Couldn't determine a path for the index cache "
             'directory.',
  'stream': 'stderr',
  'type': 'output'},
 {'message': 'thread-group-added',
  'payload': {'id': 'i1'},
  'stream': 'stdout',
  'token': None,
  'type': 'notify'},
 {'message': 'done',
  'payload': None,
  'stream': 'stdout',
  'token': None,
  'type': 'result'}]
2022-06-01 15:15:52,800 - Gdb - INFO - NOTIFY: thread-group-added {'id': 'i1'}
2022-06-01 15:15:52,800 - Gdb - DEBUG - RESULT: done None
2022-06-01 15:15:52,801 - Gdb - DEBUG - MI->: -gdb-set logging file C:\Users\MAX\AppData\Local\Temp\gdb_proc.log
2022-06-01 15:15:52,811 - Gdb - DEBUG - MI<-:
[{'message': 'done',
  'payload': None,
  'stream': 'stdout',
  'token': None,
  'type': 'result'}]
2022-06-01 15:15:52,811 - Gdb - DEBUG - RESULT: done None
2022-06-01 15:15:52,811 - Gdb - DEBUG - MI->: -gdb-set logging on
2022-06-01 15:15:52,826 - Gdb - DEBUG - MI<-:
[{'message': 'done',
  'payload': None,
  'stream': 'stdout',
  'token': None,
  'type': 'result'}]
2022-06-01 15:15:52,826 - Gdb - DEBUG - RESULT: done None
2022-06-01 15:15:52,827 - Gdb - DEBUG - MI->: -gdb-set arch riscv:rv32
2022-06-01 15:15:52,842 - Gdb - DEBUG - MI<-:
[{'message': None,
  'payload': 'The target architecture is assumed to be riscv:rv32\\n',
  'stream': 'stdout',
  'type': 'console'},
 {'message': 'done',
  'payload': None,
  'stream': 'stdout',
  'token': None,
  'type': 'result'}]
2022-06-01 15:15:52,842 - Gdb - INFO - CONS: 'The target architecture is assumed to be riscv:rv32\\n'
2022-06-01 15:15:52,842 - Gdb - DEBUG - RESULT: done None
2022-06-01 15:15:52,842 - Debug Adapter (main) - DEBUG - Created gdb object of type: GdbEsp32c3
2022-06-01 15:15:52,843 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Created gdb object of type: GdbEsp32c3\n", "source": {}}, "seq": 6}

2022-06-01 15:15:52,843 - Gdb - DEBUG - MI->: -file-exec-and-symbols c:/Users/MAX/WORK/esp32/blink/build/blink.elf
2022-06-01 15:15:52,904 - Gdb - DEBUG - MI<-:
[{'message': 'done',
  'payload': None,
  'stream': 'stdout',
  'token': None,
  'type': 'result'}]
2022-06-01 15:15:52,904 - Gdb - DEBUG - RESULT: done None
2022-06-01 15:15:52,904 - Gdb - DEBUG - Connecting to 127.0.0.1:3333
2022-06-01 15:15:52,905 - Gdb - DEBUG - MI->: -target-select remote 127.0.0.1:3333
2022-06-01 15:16:02,905 - Gdb - DEBUG - MI<-:
[{'message': None,
  'payload': 'Ignoring packet error, continuing...\\n',
  'stream': 'stdout',
  'type': 'console'},
 {'message': None,
  'payload': 'warning: unrecognized item \\"timeout\\" in \\"qSupported\\" '
             'response\\n',
  'stream': 'stdout',
  'type': 'log'}]
2022-06-01 15:16:02,905 - Gdb - INFO - CONS: 'Ignoring packet error, continuing...\\n'
2022-06-01 15:16:02,905 - Gdb - DEBUG - LOG: 'warning: unrecognized item \\"timeout\\" in \\"qSupported\\" response\\n'
2022-06-01 15:16:02,906 - Debug Adapter (main) - ERROR - Failed to wait for completion of command "-target-select remote 127.0.0.1:3333" / 10!
Traceback (most recent call last):
  File "c:\Users\MAX\.vscode\extensions\espressif.esp-idf-extension-1.4.0\esp_debug_adapter\debug_adapter\command_processor.py", line 51, in __call__
    on_request(protocol_message)
  File "c:\Users\MAX\.vscode\extensions\espressif.esp-idf-extension-1.4.0\esp_debug_adapter\debug_adapter\command_processor.py", line 74, in on_initialize_request
    raise e
  File "c:\Users\MAX\.vscode\extensions\espressif.esp-idf-extension-1.4.0\esp_debug_adapter\debug_adapter\command_processor.py", line 69, in on_initialize_request
    self.da.adapter_init()
  File "c:\Users\MAX\.vscode\extensions\espressif.esp-idf-extension-1.4.0\esp_debug_adapter\debug_adapter\debug_adapter.py", line 315, in adapter_init
    raise e
  File "c:\Users\MAX\.vscode\extensions\espressif.esp-idf-extension-1.4.0\esp_debug_adapter\debug_adapter\debug_adapter.py", line 311, in adapter_init
    self.start_gdb()
  File "c:\Users\MAX\.vscode\extensions\espressif.esp-idf-extension-1.4.0\esp_debug_adapter\debug_adapter\debug_adapter.py", line 542, in start_gdb
    raise e
  File "c:\Users\MAX\.vscode\extensions\espressif.esp-idf-extension-1.4.0\esp_debug_adapter\debug_adapter\debug_adapter.py", line 539, in start_gdb
    self._gdb.connect()
  File "c:\Users\MAX\.vscode\extensions\espressif.esp-idf-extension-1.4.0\esp_debug_adapter\debug_adapter\debug_backend\debug_backend\gdb.py", line 551, in connect
    self.target_select(remote_mode, self._remote_target, tmo=tmo)
  File "c:\Users\MAX\.vscode\extensions\espressif.esp-idf-extension-1.4.0\esp_debug_adapter\debug_adapter\debug_backend\debug_backend\gdb.py", line 250, in target_select
    res, _ = self._mi_cmd_run('-target-select %s %s' % (tgt_type, tgt_params),
  File "c:\Users\MAX\.vscode\extensions\espressif.esp-idf-extension-1.4.0\esp_debug_adapter\debug_adapter\debug_backend\debug_backend\gdb.py", line 201, in _mi_cmd_run
    raise DebuggerTargetStateTimeoutError(
debug_adapter.debug_backend.debug_backend.defs.DebuggerTargetStateTimeoutError: Failed to wait for completion of command "-target-select remote 127.0.0.1:3333" / 10!
2022-06-01 15:16:02,906 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "response", "request_seq": 1, "success": false, "command": "initialize", "seq": 7, "message": "Failed to init Debug Adapter!", "body": {}}

2022-06-01 15:16:02,909 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Failed to wait for completion of command \"-target-select remote 127.0.0.1:3333\" / 10!\n", "source": {}}, "seq": 8}

2022-06-01 15:16:02,909 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Failed to wait for completion of command \"-target-select remote 127.0.0.1:3333\" / 10!\n", "source": {}}, "seq": 9}

2022-06-01 15:16:02,962 - Debug Adapter (ReaderThread) - DEBUG - read line: >>b'Content-Length: 79\\r\\n'<<

2022-06-01 15:16:02,962 - Debug Adapter (ReaderThread) - DEBUG - read line: >>b'\\r\\n'<<

2022-06-01 15:16:02,963 - Debug Adapter(Command Processor) - DEBUG - Got json: {
    "arguments": {
        "restart": false
    },
    "command": "disconnect",
    "seq": 2,
    "type": "request"
}
2022-06-01 15:16:02,963 - Debug Adapter (main) - DEBUG - Adapter is Stopping...
2022-06-01 15:16:02,964 - Debug Adapter (main) - DEBUG - Stopping target poller
2022-06-01 15:16:02,964 - Debug Adapter (main) - DEBUG - Closing the GDB process
2022-06-01 15:16:02,965 - Debug Adapter (main) - DEBUG - Closing the Socket
2022-06-01 15:16:02,965 - Debug Adapter (main) - DEBUG - Stopping of the Writer thread
2022-06-01 15:16:02,972 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Got json: {\n    \"arguments\": {\n        \"restart\": false\n    },\n    \"command\": \"disconnect\",\n    \"seq\": 2,\n    \"type\": \"request\"\n}\n", "source": {}}, "seq": 10}

2022-06-01 15:16:02,980 - Debug Adapter (main) - DEBUG - Stopping of the Reader thread
2022-06-01 15:16:02,980 - Debug Adapter (main) - DEBUG - Adapter is Stopped
DEBUG_ADAPTER_STOPPED
2022-06-01 15:16:02,980 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_STOPPED
2022-06-01 15:16:02,981 - Debug Adapter(Command Processor) - DEBUG - Processed command: disconnect
[Stopped] : ESP-IDF Debug Adapter
```

**Comment by WangShuoran** [comment]
I meet same question, but in esp-idf v4.3.2 and this repo v1.2.0 the esp32c3 built-in jtag is ok

**Comment by WangShuoran** [comment]
and the esp32s3 built in jtag have no response. the error scene is not same with esp32c3 built-in jtag

**Comment by WangShuoran** [comment]
I am use clear Windows system. And use IDF install tools install esp-idf v4.4.1, the v4.3.2 in another PC. This system not have python, but idf default python version is 3.8, `idf4.4_py3.8_env`, I want to give you any detail info. Can you tell me you need info?

**Comment by brianignacio5** [comment]
Could you try increasing the timeout in your project's launch.json by setting `tmoScaleFactor: 2` or other value (default is 1). Based on the latest debug adapter log, seems like a timing issue.

as seen in [Debugging doc](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/DEBUGGING.md)

**Comment by WangShuoran** [comment]
@brianignacio5

**Comment by brianignacio5** [comment]
@WangShuoran  I need the same information given by @ScarsFun 

Also have you tried `tmoScaleFactor: 2` ?

**Comment by WangShuoran** [comment]
https://github.com/espressif/openocd-esp32/issues/236#issuecomment-1179686968

**Comment by brianignacio5** [comment]
I'm closing this issue from lack of response from original user.
