### ISSUE TITLE
Extension fails to install PIP packages

### ISSUE THREAD

**Issue by beta-tester** [espressif/vscode-esp-idf-extension#841]
### OS

Linux

### Operating System version

Ubuntu 22.10 amd64

### Visual Studio Code version

1.73.1 (snap)

### ESP-IDF version

4.4.3

### Python version

3.10.6

### Doctor command output

does not execute !

### Extension

1.5.1

### Description

on my PC i installed Ubuntu 22.10 and VS Code from snap via`sudo snap install --classic code`.
i can install Espressif ESP-IDF Extension ind VS Code, but when i try to do a n Express setup it fails on installing some PIP packages.

![ubuntu-02](https://user-images.githubusercontent.com/4750719/201677035-d14f7c55-6028-49d9-a3a7-00a9dd23f2d8.png)

see the log below (i removed all the lines with percentag of progress)

### Debug Message

```plain
idf_versions.txt has (1) KB
Downloading ESP-IDF v4.4.3 (release version)...
esp-idf-v4.4.3.zip has (999272) KB
Downloaded v4.4.3 (release version). Extracting...

Extracted /home/me/esp/esp-idf-v4.4.3.zip in /home/me/esp.


Entering 'components/asio/asio'
Entering 'components/bootloader/subproject/components/micro-ecc/micro-ecc'
Entering 'components/bt/controller/lib_esp32'
Entering 'components/bt/controller/lib_esp32c3_family'
Entering 'components/bt/host/nimble/nimble'
Entering 'components/cbor/tinycbor'
Entering 'components/cmock/CMock'
Entering 'components/cmock/CMock/vendor/c_exception'
Entering 'components/cmock/CMock/vendor/unity'
Entering 'components/coap/libcoap'
Entering 'components/coap/libcoap/ext/tinydtls'
Entering 'components/esp_phy/lib'
Entering 'components/esp_wifi/lib'
Entering 'components/esptool_py/esptool'
Entering 'components/expat/expat'
Entering 'components/ieee802154/lib'
Entering 'components/json/cJSON'
Entering 'components/libsodium/libsodium'
Entering 'components/lwip/lwip'
Entering 'components/mbedtls/mbedtls'
Entering 'components/mqtt/esp-mqtt'
Entering 'components/nghttp/nghttp2'
Entering 'components/nghttp/nghttp2/third-party/mruby'
Entering 'components/nghttp/nghttp2/third-party/neverbleed'
Entering 'components/openthread/lib'
Entering 'components/openthread/openthread'
Entering 'components/protobuf-c/protobuf-c'
Entering 'components/spiffs/spiffs'
Entering 'components/tinyusb/tinyusb'
Entering 'components/unity/unity'
Entering 'examples/build_system/cmake/import_lib/main/lib/tinyxml2'
Entering 'examples/peripherals/secure_element/atecc608_ecdsa/components/esp-cryptoauthlib'


HEAD is now at 6407ecb3f8 versions: Update version to 4.4.3


/bin/sh: 1: openocd: not found
Command failed: openocd --version
/bin/sh: 1: openocd: not found
Error checking openocd-esp32 version
Error: Command failed: openocd --version
/bin/sh: 1: openocd: not found

/bin/sh: 1: esp32ulp-elf-as: not found
Command failed: esp32ulp-elf-as --version
/bin/sh: 1: esp32ulp-elf-as: not found
Error checking esp32ulp-elf version
Error: Command failed: esp32ulp-elf-as --version
/bin/sh: 1: esp32ulp-elf-as: not found

/bin/sh: 1: riscv32-esp-elf-gcc: not found
Command failed: riscv32-esp-elf-gcc --version
/bin/sh: 1: riscv32-esp-elf-gcc: not found
Error checking riscv32-esp-elf version
Error: Command failed: riscv32-esp-elf-gcc --version
/bin/sh: 1: riscv32-esp-elf-gcc: not found

/bin/sh: 1: xtensa-esp32s3-elf-gcc: not found
Command failed: xtensa-esp32s3-elf-gcc --version
/bin/sh: 1: xtensa-esp32s3-elf-gcc: not found
Error checking xtensa-esp32s3-elf version
Error: Command failed: xtensa-esp32s3-elf-gcc --version
/bin/sh: 1: xtensa-esp32s3-elf-gcc: not found

/bin/sh: 1: xtensa-esp32s2-elf-gcc: not found
Command failed: xtensa-esp32s2-elf-gcc --version
/bin/sh: 1: xtensa-esp32s2-elf-gcc: not found
Error checking xtensa-esp32s2-elf version
Error: Command failed: xtensa-esp32s2-elf-gcc --version
/bin/sh: 1: xtensa-esp32s2-elf-gcc: not found

/bin/sh: 1: xtensa-esp32-elf-gcc: not found
Command failed: xtensa-esp32-elf-gcc --version
/bin/sh: 1: xtensa-esp32-elf-gcc: not found
Error checking xtensa-esp32-elf version
Error: Command failed: xtensa-esp32-elf-gcc --version
/bin/sh: 1: xtensa-esp32-elf-gcc: not found


Downloading Toolchain for Xtensa (ESP32) based on GCC
xtensa-esp32-elf-gcc8_4_0-esp-2021r2-patch5-linux-amd64.tar.gz has (92186) KB
Downloading Toolchain for Xtensa (ESP32-S2) based on GCC
xtensa-esp32s2-elf-gcc8_4_0-esp-2021r2-patch5-linux-amd64.tar.gz has (66259) KB
Downloading Toolchain for Xtensa (ESP32-S3) based on GCC
xtensa-esp32s3-elf-gcc8_4_0-esp-2021r2-patch5-linux-amd64.tar.gz has (66504) KB
Downloading Toolchain for 32-bit RISC-V based on GCC
riscv32-esp-elf-gcc8_4_0-esp-2021r2-patch5-linux-amd64.tar.gz has (187880) KB
Downloading Toolchain for ESP32 ULP coprocessor
esp32ulp-elf-2.35_20220830-linux-amd64.tar.gz has (10435) KB
Downloading CMake build system
cmake-3.23.1-linux-x86_64.tar.gz has (44921) KB
Downloading OpenOCD for ESP32
openocd-esp32-linux-amd64-0.11.0-esp32-20220706.tar.gz has (1965) KB
Downloading Ninja build system
ninja-1.10.2-linux64.tar.gz has (104) KB

Installing package Toolchain for Xtensa (ESP32) based on GCC
Installing tar.gz package Toolchain for Xtensa (ESP32) based on GCC
Installing package Toolchain for Xtensa (ESP32-S2) based on GCC
Installing tar.gz package Toolchain for Xtensa (ESP32-S2) based on GCC
Installing package Toolchain for Xtensa (ESP32-S3) based on GCC
Installing tar.gz package Toolchain for Xtensa (ESP32-S3) based on GCC
Installing package Toolchain for 32-bit RISC-V based on GCC
Installing tar.gz package Toolchain for 32-bit RISC-V based on GCC
Installing package Toolchain for ESP32 ULP coprocessor
Installing tar.gz package Toolchain for ESP32 ULP coprocessor
Installing package CMake build system
Installing tar.gz package CMake build system
Installing package OpenOCD for ESP32
Installing tar.gz package OpenOCD for ESP32
Installing package Ninja build system
Installing tar.gz package Ninja build system

Collecting virtualenv
  Downloading virtualenv-20.16.7-py3-none-any.whl (8.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 5.3 MB/s eta 0:00:00
Collecting platformdirs<3,>=2.4
  Downloading platformdirs-2.5.4-py3-none-any.whl (14 kB)
Collecting distlib<1,>=0.3.6
  Downloading distlib-0.3.6-py2.py3-none-any.whl (468 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.5/468.5 kB 5.2 MB/s eta 0:00:00
Collecting filelock<4,>=3.4.1
  Downloading filelock-3.8.0-py3-none-any.whl (10 kB)
Installing collected packages: distlib, platformdirs, filelock, virtualenv
Successfully installed distlib-0.3.6 filelock-3.8.0 platformdirs-2.5.4 virtualenv-20.16.7
--- Logging error ---
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.10/site-packages/pip/_internal/utils/logging.py", line 177, in emit
    self.console.print(renderable, overflow="ignore", crop=False, style=style)
  File "/home/me/.local/lib/python3.10/site-packages/pip/_vendor/rich/console.py", line 1752, in print
    extend(render(renderable, render_options))
  File "/home/me/.local/lib/python3.10/site-packages/pip/_vendor/rich/console.py", line 1390, in render
    for render_output in iter_render:
  File "/home/me/.local/lib/python3.10/site-packages/pip/_internal/utils/logging.py", line 134, in __rich_console__
    for line in lines:
  File "/home/me/.local/lib/python3.10/site-packages/pip/_vendor/rich/segment.py", line 245, in split_lines
    for segment in segments:
  File "/home/me/.local/lib/python3.10/site-packages/pip/_vendor/rich/console.py", line 1368, in render
    renderable = rich_cast(renderable)
  File "/home/me/.local/lib/python3.10/site-packages/pip/_vendor/rich/protocol.py", line 36, in rich_cast
    renderable = cast_method()
  File "/home/me/.local/lib/python3.10/site-packages/pip/_internal/self_outdated_check.py", line 130, in __rich__
    pip_cmd = get_best_invocation_for_this_pip()
  File "/home/me/.local/lib/python3.10/site-packages/pip/_internal/utils/entrypoints.py", line 58, in get_best_invocation_for_this_pip
    if found_executable and os.path.samefile(
  File "/usr/lib/python3.10/genericpath.py", line 101, in samefile
    s2 = os.stat(f2)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip'
Call stack:
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/me/.local/lib/python3.10/site-packages/pip/__main__.py", line 31, in <module>
    sys.exit(_main())
  File "/home/me/.local/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 70, in main
    return command.main(cmd_args)
  File "/home/me/.local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
  File "/home/me/.local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    self.handle_pip_version_check(options)
  File "/home/me/.local/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 148, in handle_pip_version_check
    pip_self_version_check(session, options)
  File "/home/me/.local/lib/python3.10/site-packages/pip/_internal/self_outdated_check.py", line 237, in pip_self_version_check
    logger.info("[present-rich] %s", upgrade_prompt)
  File "/usr/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/home/me/.local/lib/python3.10/site-packages/pip/_internal/utils/logging.py", line 179, in emit
    self.handleError(record)
Message: '[present-rich] %s'
Arguments: (UpgradePrompt(old='22.1.2', new='22.3.1'),)
Error during ESP-IDF setup
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by beta-tester** [comment]
sorry. the issue was on my site.
the snap installation of blender screwed up pip.
```
$ pip --version
bash: /home/me/.local/bin/pip: /snap/blender/2106/3.1/python/bin/python3.10: bad interpreter: No such file or directory

$ /usr/bin/pip --version
bash: /usr/bin/pip: Datei oder Verzeichnis nicht gefunden

$ sudo apt install python3-pip
...

$ /usr/bin/pip --version
pip 22.1.2 from /home/me/.local/lib/python3.10/site-packages/pip (python 3.10)
```

i reinstalled pip with `sudo apt install python3-pip` and now the Espressif ESP-IDF Extension works well.

**Comment by beta-tester** [comment]
maybe the package `python3-pip` should be in the list of requirements as well to get installed.
