### ISSUE TITLE
[esp32c3-builtin] ERROR - Failed to wait for completion of command (VSC-1056)

### ISSUE THREAD

**Issue by matsujirushi** [espressif/vscode-esp-idf-extension#899]
### OS

Windows

### Operating System version

Windows 11 22H2

### Visual Studio Code version

1.75.1

### ESP-IDF version

4.4.4

### Python version

3.8.7

### Doctor command output

```
---------------------------------------------- ESP-IDF Extension for Visual Studio Code report ---------------------------------------------
OS win32 x64 10.0.22621 
System environment variable IDF_PYTHON_ENV_PATH 
 undefined 
System environment variable PATH 
 C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Microsoft Azure Sphere SDK\Tools_v2\wbin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Python38-32\Scripts\;C:\Program Files (x86)\Python38-32\;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Azure Data Studio\bin;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\SEGGER\JLink;C:\Program Files\Nordic Semiconductor\nrf-command-line-tools\bin\;C:\Program Files (x86)\Mercurial;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Go\bin;C:\tinygo\bin;;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files (x86)\GNU Tools ARM Embedded\6 2017-q2-update\bin;C:<HOMEPATH>\AppData\Local\Microsoft\WindowsApps;C:<HOMEPATH>\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\arduino-cli;C:\Program Files\Azure Data Studio\bin;C:<HOMEPATH>\AppData\Roaming\npm;C:<HOMEPATH>\.dotnet\tools;C:<HOMEPATH>\go\bin 
System environment variable PYTHON 
 undefined 
Visual Studio Code version 1.75.1 
Visual Studio Code language ja 
Visual Studio Code shell C:\WINDOWS\System32\cmd.exe 
ESP-IDF Extension version 1.5.1 
Workspace folder c:<HOMEPATH>\esp\blink 
---------------------------------------------------- Extension configuration settings ------------------------------------------------------
ESP-ADF Path (idf.espAdfPath) ${env:ADF_PATH}
ESP-IDF Path (idf.espIdfPath) C:<HOMEPATH>\esp\esp-idf
ESP-MDF Path (idf.espMdfPath) ${env:MDF_PATH}
ESP-Matter Path (idf.espMatterPath) ${env:ESP_MATTER_PATH}
Custom extra paths (idf.customExtraPaths) C:<HOMEPATH>\.espressif\tools\xtensa-esp-elf-gdb\11.2_20220823\xtensa-esp-elf-gdb\bin;C:<HOMEPATH>\.espressif\tools\riscv32-esp-elf-gdb\11.2_20220823\riscv32-esp-elf-gdb\bin;C:<HOMEPATH>\.espressif\tools\xtensa-esp32-elf\esp-2021r2-patch5-8.4.0\xtensa-esp32-elf\bin;C:<HOMEPATH>\.espressif\tools\xtensa-esp32s2-elf\esp-2021r2-patch5-8.4.0\xtensa-esp32s2-elf\bin;C:<HOMEPATH>\.espressif\tools\xtensa-esp32s3-elf\esp-2021r2-patch5-8.4.0\xtensa-esp32s3-elf\bin;C:<HOMEPATH>\.espressif\tools\riscv32-esp-elf\esp-2021r2-patch5-8.4.0\riscv32-esp-elf\bin;C:<HOMEPATH>\.espressif\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin;C:<HOMEPATH>\.espressif\tools\cmake\3.23.1\bin;C:<HOMEPATH>\.espressif\tools\openocd-esp32\v0.11.0-esp32-20221026\openocd-esp32\bin;C:<HOMEPATH>\.espressif\tools\ninja\1.10.2;C:<HOMEPATH>\.espressif\tools\idf-exe\1.0.3;C:<HOMEPATH>\.espressif\tools\ccache\4.3\ccache-4.3-windows-64;C:<HOMEPATH>\.espressif\tools\dfu-util\0.9\dfu-util-0.9-win64
Custom extra vars (idf.customExtraVars) {"OPENOCD_SCRIPTS":"C:\\Users\\takashi\\.espressif\\tools\\openocd-esp32\\v0.11.0-esp32-20221026/openocd-esp32/share/openocd/scripts","IDF_CCACHE_ENABLE":"1"}
Virtual env Python Path (idf.pythonBinPath) C:<HOMEPATH>\.espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe
Serial port (idf.port) COM14
OpenOCD Configs (idf.openOcdConfigs) board/esp32c3-builtin.cfg
ESP-IDF Tools Path (idf.toolsPath) C:<HOMEPATH>\.espressif
Git Path (idf.gitPath) C:<HOMEPATH>\.espressif\tools\idf-git\2.30.1\cmd\git.exe
-------------------------------------------------------- Configurations access -------------------------------------------------------------
Access to ESP-ADF Path (idf.espAdfPath) false
Access to ESP-IDF Path (idf.espIdfPath) true
Access to ESP-MDF Path (idf.espMdfPath) false
Access to ESP-Matter Path (idf.espMatterPath) false
Access to ESP-IDF Custom extra paths
Access to C:<HOMEPATH>\.espressif\tools\xtensa-esp-elf-gdb\11.2_20220823\xtensa-esp-elf-gdb\bin: true
Access to C:<HOMEPATH>\.espressif\tools\riscv32-esp-elf-gdb\11.2_20220823\riscv32-esp-elf-gdb\bin: true
Access to C:<HOMEPATH>\.espressif\tools\xtensa-esp32-elf\esp-2021r2-patch5-8.4.0\xtensa-esp32-elf\bin: true
Access to C:<HOMEPATH>\.espressif\tools\xtensa-esp32s2-elf\esp-2021r2-patch5-8.4.0\xtensa-esp32s2-elf\bin: true
Access to C:<HOMEPATH>\.espressif\tools\xtensa-esp32s3-elf\esp-2021r2-patch5-8.4.0\xtensa-esp32s3-elf\bin: true
Access to C:<HOMEPATH>\.espressif\tools\riscv32-esp-elf\esp-2021r2-patch5-8.4.0\riscv32-esp-elf\bin: true
Access to C:<HOMEPATH>\.espressif\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin: true
Access to C:<HOMEPATH>\.espressif\tools\cmake\3.23.1\bin: true
Access to C:<HOMEPATH>\.espressif\tools\openocd-esp32\v0.11.0-esp32-20221026\openocd-esp32\bin: true
Access to C:<HOMEPATH>\.espressif\tools\ninja\1.10.2: true
Access to C:<HOMEPATH>\.espressif\tools\idf-exe\1.0.3: true
Access to C:<HOMEPATH>\.espressif\tools\ccache\4.3\ccache-4.3-windows-64: true
Access to C:<HOMEPATH>\.espressif\tools\dfu-util\0.9\dfu-util-0.9-win64: true
Access to Virtual env Python Path (idf.pythonBinPath) true
Access to CMake in environment PATH undefined
Access to Ninja in environment PATH undefined
Access to ESP-IDF Tools Path (idf.toolsPath) true
-------------------------------------------------------- Configurations has spaces -------------------------------------------------------------
Spaces in system environment Path true
Spaces in ESP-ADF Path (idf.espAdfPath) false
Spaces in ESP-IDF Path (idf.espIdfPath) false
Spaces in ESP-MDF Path (idf.espMdfPath) false
Spaces in ESP-Matter Path (idf.espMatterPath) false
Spaces in ESP-IDF Custom extra paths
Spaces in C:<HOMEPATH>\.espressif\tools\xtensa-esp-elf-gdb\11.2_20220823\xtensa-esp-elf-gdb\bin: false
Spaces in C:<HOMEPATH>\.espressif\tools\riscv32-esp-elf-gdb\11.2_20220823\riscv32-esp-elf-gdb\bin: false
Spaces in C:<HOMEPATH>\.espressif\tools\xtensa-esp32-elf\esp-2021r2-patch5-8.4.0\xtensa-esp32-elf\bin: false
Spaces in C:<HOMEPATH>\.espressif\tools\xtensa-esp32s2-elf\esp-2021r2-patch5-8.4.0\xtensa-esp32s2-elf\bin: false
Spaces in C:<HOMEPATH>\.espressif\tools\xtensa-esp32s3-elf\esp-2021r2-patch5-8.4.0\xtensa-esp32s3-elf\bin: false
Spaces in C:<HOMEPATH>\.espressif\tools\riscv32-esp-elf\esp-2021r2-patch5-8.4.0\riscv32-esp-elf\bin: false
Spaces in C:<HOMEPATH>\.espressif\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin: false
Spaces in C:<HOMEPATH>\.espressif\tools\cmake\3.23.1\bin: false
Spaces in C:<HOMEPATH>\.espressif\tools\openocd-esp32\v0.11.0-esp32-20221026\openocd-esp32\bin: false
Spaces in C:<HOMEPATH>\.espressif\tools\ninja\1.10.2: false
Spaces in C:<HOMEPATH>\.espressif\tools\idf-exe\1.0.3: false
Spaces in C:<HOMEPATH>\.espressif\tools\ccache\4.3\ccache-4.3-windows-64: false
Spaces in C:<HOMEPATH>\.espressif\tools\dfu-util\0.9\dfu-util-0.9-win64: false
Spaces in Virtual env Python Path (idf.pythonBinPath) false
Spaces in ESP-IDF Tools Path (idf.toolsPath) false
----------------------------------------------------------- Executables Versions -----------------------------------------------------------
Git version 2.30.1.windows.1
ESP-IDF version 4.4.4
Python version 3.8.7
Python's pip version 20.3.3
-------------------------------------------------- Python packages in idf.pythonBinPath ----------------------------------------------------
bitstring version: 3.1.9
Brotli version: 1.0.9
CacheControl version: 0.12.11
certifi version: 2022.12.7
cffi version: 1.15.1
charset-normalizer version: 3.0.1
click version: 8.0.4
colorama version: 0.4.6
construct version: 2.10.54
contextlib2 version: 21.6.0
cryptography version: 39.0.1
ecdsa version: 0.18.0
esp-windows-curses version: 0.1
Flask version: 0.12.5
Flask-Compress version: 1.13
Flask-SocketIO version: 2.9.6
future version: 0.18.2
gcovr version: 5.2
gdbgui version: 0.13.2.0
gevent version: 1.5.0
greenlet version: 2.0.2
idf-component-manager version: 1.2.2
idna version: 3.4
itsdangerous version: 2.0.1
Jinja2 version: 3.0.3
kconfiglib version: 13.7.1
lockfile version: 0.12.2
lxml version: 4.9.2
MarkupSafe version: 2.1.2
msgpack version: 1.0.4
packaging version: 23.0
pip version: 20.3.3
psutil version: 5.9.4
pycparser version: 2.21
pyelftools version: 0.29
pygdbmi version: 0.9.0.2
Pygments version: 2.14.0
pyparsing version: 2.3.1
pyserial version: 3.5
python-engineio version: 3.14.2
python-socketio version: 4.6.1
pywin32 version: 305
PyYAML version: 6.0
reedsolo version: 1.5.4
requests version: 2.28.2
requests-file version: 1.5.1
requests-toolbelt version: 0.10.1
schema version: 0.7.5
setuptools version: 67.4.0
six version: 1.16.0
tqdm version: 4.64.1
urllib3 version: 1.26.14
websocket-client version: 1.5.1
Werkzeug version: 0.16.1
wheel version: 0.36.2
windows-curses version: 2.3.1
xmlrunner version: 1.7.7
---------------------------------------------------- Check ESP-IDF python requirements.txt -------------------------------------------------
Check ESP-IDF Python packages Python requirements from C:<HOMEPATH>\esp\esp-idf\requirements.txt are satisfied.
---------------------------------------------------- Check extension requirements.txt ------------------------------------------------------
Check Extension Python packages Python requirements from c:<HOMEPATH>\.vscode\extensions\espressif.esp-idf-extension-1.5.1\requirements.txt are satisfied.
---------------------------------------------------- Check ESP-IDF debug adapter requirements.txt ------------------------------------------
Check Debug AdapterPython packages Python requirements from c:<HOMEPATH>\.vscode\extensions\espressif.esp-idf-extension-1.5.1\esp_debug_adapter\requirements.txt are satisfied.
---------------------------------------------------- Visual Studio Code launch.json --------------------------------------------------------
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "espidf",
      "name": "Launch",
      "request": "launch",
      "logLevel": 4
    }
  ]
} 
---------------------------------------------------- Visual Studio Code c_cpp_properties.json ----------------------------------------------
{
    "configurations": [
        {
            "name": "ESP-IDF",
            "compilerPath": "C:\\Users\\takashi\\.espressif\\tools\\xtensa-esp32-elf\\esp-2021r2-patch5-8.4.0\\xtensa-esp32-elf\\bin\\xtensa-esp32-elf-gcc.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "includePath": [
                "${config:idf.espIdfPath}/components/**",
                "${config:idf.espIdfPathWin}/components/**",
                "${config:idf.espAdfPath}/components/**",
                "${config:idf.espAdfPathWin}/components/**",
                "${workspaceFolder}/**"
            ],
            "browse": {
                "path": [
                    "${config:idf.espIdfPath}/components",
                    "${config:idf.espIdfPathWin}/components",
                    "${config:idf.espAdfPath}/components/**",
                    "${config:idf.espAdfPathWin}/components/**",
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": false
            }
        }
    ],
    "version": 4
}
 
--------------------------------------------------------------------------------------------------------------------------------------------
```

### Description

"ERROR - Failed to wait for completion of command" occurs when debugging is started on a specific PC.

**Steps to get the error:**

1. Start OpenOCD Server (Click the icon on status bar)
2. Start debugging my application (F5)

**Error-free steps:**

1. Start OpenOCD Server (Click the icon on status bar)
2. Start debugging my application using ESP-IDF Terminal ("riscv32-esp-elf-gdb -x gdbinit build/blink.elf")

It looks like Debug Adapter can't communicate to OpenOCD.
But I don't know how to find out.

Please give me some advice.

### Debug Message

```plain
[Debug Adapter]
2023-02-28 09:29:23,712 - Debug Adapter (main) - DEBUG - START_TIME_2023_02_28_09-29-23
2023-02-28 09:29:23,712 - Debug Adapter (main) - DEBUG - Init errors:None
2023-02-28 09:29:23,712 - Debug Adapter (main) - INFO - Working directory: C:\Users\takashi\AppData\Local\Programs\Microsoft VS Code
2023-02-28 09:29:23,713 - Debug Adapter (main) - INFO - Arguments: 
{   'app_flash_off': 65536,
    'board_type': None,
    'cmdfile': None,
    'core_file': (),
    'debug': 4,
    'developer_mode': 'none',
    'device_name': 'esp32c3',
    'elfpath': ('c:\\Users\\takashi\\esp\\blink\\build\\blink.elf',),
    'log_file': 'c:\\Users\\takashi\\esp\\blink\\debug.log',
    'log_mult_files': None,
    'log_no_debug_console': None,
    'oocd': 'openocd',
    'oocd_args': None,
    'oocd_ip': 'localhost',
    'oocd_mode': 'connect_to_instance',
    'oocd_scripts': None,
    'port': 43474,
    'postmortem': False,
    'tmo_scale_factor': 1,
    'toolchain_prefix': 'riscv32-esp-elf-'}
DEBUG_ADAPTER_STARTED
2023-02-28 09:29:23,713 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_STARTED
2023-02-28 09:29:23,713 - Debug Adapter (main) - INFO - Starting. Cmd: c:\Users\takashi\.vscode\extensions\espressif.esp-idf-extension-1.5.1\esp_debug_adapter\debug_adapter_main.py -d 4 -e c:\Users\takashi\esp\blink\build\blink.elf -l c:\Users\takashi\esp\blink\debug.log -p 43474 -dn esp32c3 -a 0x10000 -t riscv32-esp-elf-

[Debug Adapter]
2023-02-28 09:29:23,718 - Debug Adapter (main) - INFO - Listening on port 43474
DEBUG_ADAPTER_READY2CONNECT
2023-02-28 09:29:23,718 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_READY2CONNECT
[Debug Adapter]
2023-02-28 09:29:23,724 - Debug Adapter (main) - DEBUG - Got connection
2023-02-28 09:29:23,726 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Debug adapter -> Extension: DEBUG_ADAPTER_STARTED\n", "source": {}}, "seq": 0}

2023-02-28 09:29:23,726 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Starting. Cmd: c:\\Users\\takashi\\.vscode\\extensions\\espressif.esp-idf-extension-1.5.1\\esp_debug_adapter\\debug_adapter_main.py -d 4 -e c:\\Users\\takashi\\esp\\blink\\build\\blink.elf -l c:\\Users\\takashi\\esp\\blink\\debug.log -p 43474 -dn esp32c3 -a 0x10000 -t riscv32-esp-elf-\n\n", "source": {}}, "seq": 1}

2023-02-28 09:29:23,726 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Listening on port 43474\n", "source": {}}, "seq": 2}

2023-02-28 09:29:23,726 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Debug adapter -> Extension: DEBUG_ADAPTER_READY2CONNECT\n", "source": {}}, "seq": 3}

2023-02-28 09:29:23,727 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Got connection\n", "source": {}}, "seq": 4}

[Debug Adapter]
2023-02-28 09:29:23,738 - Debug Adapter (ReaderThread) - DEBUG - read line: >>b'Content-Length: 477\\r\\n'<<

2023-02-28 09:29:23,738 - Debug Adapter (ReaderThread) - DEBUG - read line: >>b'\\r\\n'<<

2023-02-28 09:29:23,738 - Debug Adapter(Command Processor) - DEBUG - Got json: {
    "arguments": {
        "adapterID": "espidf",
        "clientID": "vscode",
        "clientName": "Visual Studio Code",
        "columnsStartAt1": true,
        "linesStartAt1": true,
        "locale": "ja",
        "pathFormat": "path",
        "supportsArgsCanBeInterpretedByShell": true,
        "supportsInvalidatedEvent": true,
        "supportsMemoryEvent": true,
        "supportsMemoryReferences": true,
        "supportsProgressReporting": true,
        "supportsRunInTerminalRequest": true,
        "supportsVariablePaging": true,
        "supportsVariableType": true
    },
    "command": "initialize",
    "seq": 1,
    "type": "request"
}
[Debug Adapter]
2023-02-28 09:29:23,739 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Got json: {\n    \"arguments\": {\n        \"adapterID\": \"espidf\",\n        \"clientID\": \"vscode\",\n        \"clientName\": \"Visual Studio Code\",\n        \"columnsStartAt1\": true,\n        \"linesStartAt1\": true,\n        \"locale\": \"ja\",\n        \"pathFormat\": \"path\",\n        \"supportsArgsCanBeInterpretedByShell\": true,\n        \"supportsInvalidatedEvent\": true,\n        \"supportsMemoryEvent\": true,\n        \"supportsMemoryReferences\": true,\n        \"supportsProgressReporting\": true,\n        \"supportsRunInTerminalRequest\": true,\n        \"supportsVariablePaging\": true,\n        \"supportsVariableType\": true\n    },\n    \"command\": \"initialize\",\n    \"seq\": 1,\n    \"type\": \"request\"\n}\n", "source": {}}, "seq": 5}

[Debug Adapter]
2023-02-28 09:29:23,746 - Gdb - DEBUG - MI->: -gdb-set mi-async on
[Debug Adapter]
2023-02-28 09:29:23,987 - Gdb - DEBUG - MI<-:
[{'message': 'thread-group-added',
  'payload': {'id': 'i1'},
  'stream': 'stdout',
  'token': None,
  'type': 'notify'},
 {'message': 'done',
  'payload': None,
  'stream': 'stdout',
  'token': None,
  'type': 'result'}]
2023-02-28 09:29:23,987 - Gdb - INFO - NOTIFY: thread-group-added {'id': 'i1'}
[Debug Adapter]
2023-02-28 09:29:23,987 - Gdb - DEBUG - RESULT: done None
2023-02-28 09:29:23,987 - Gdb - DEBUG - MI->: -gdb-set logging file C:\Users\takashi\AppData\Local\Temp\gdb_proc.log
[Debug Adapter]
2023-02-28 09:29:24,010 - Gdb - DEBUG - MI<-:
[{'message': 'done',
  'payload': None,
  'stream': 'stdout',
  'token': None,
  'type': 'result'}]
2023-02-28 09:29:24,010 - Gdb - DEBUG - RESULT: done None
[Debug Adapter]
2023-02-28 09:29:24,010 - Gdb - DEBUG - MI->: -gdb-set logging on
[Debug Adapter]
2023-02-28 09:29:24,026 - Gdb - DEBUG - MI<-:
[{'message': 'done',
  'payload': None,
  'stream': 'stdout',
  'token': None,
  'type': 'result'}]
2023-02-28 09:29:24,026 - Gdb - DEBUG - RESULT: done None
[Debug Adapter]
2023-02-28 09:29:24,026 - Gdb - DEBUG - MI->: -gdb-set arch riscv:rv32
[Debug Adapter]
2023-02-28 09:29:24,042 - Gdb - DEBUG - MI<-:
[{'message': None,
  'payload': 'The target architecture is set to \\"riscv:rv32\\".\\n',
  'stream': 'stdout',
  'type': 'console'},
 {'message': 'done',
  'payload': None,
  'stream': 'stdout',
  'token': None,
  'type': 'result'}]
[Debug Adapter]
2023-02-28 09:29:24,042 - Gdb - INFO - CONS: 'The target architecture is set to \\"riscv:rv32\\".\\n'
2023-02-28 09:29:24,042 - Gdb - DEBUG - RESULT: done None
2023-02-28 09:29:24,042 - Debug Adapter (main) - DEBUG - Created gdb object of type: GdbEsp32c3
2023-02-28 09:29:24,042 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Created gdb object of type: GdbEsp32c3\n", "source": {}}, "seq": 6}

2023-02-28 09:29:24,042 - Gdb - DEBUG - MI->: -file-exec-and-symbols c:/Users/takashi/esp/blink/build/blink.elf
[Debug Adapter]
2023-02-28 09:29:29,043 - Gdb - DEBUG - MI<-:
[]
[Debug Adapter]
2023-02-28 09:29:29,044 - Debug Adapter (main) - ERROR - Failed to wait for completion of command "-file-exec-and-symbols c:/Users/takashi/esp/blink/build/blink.elf" / 5!
Traceback (most recent call last):
  File "c:\Users\takashi\.vscode\extensions\espressif.esp-idf-extension-1.5.1\esp_debug_adapter\debug_adapter\command_processor.py", line 52, in __call__
    on_request(protocol_message)
  File "c:\Users\takashi\.vscode\extensions\espressif.esp-idf-extension-1.5.1\esp_debug_adapter\debug_adapter\command_processor.py", line 75, in on_initialize_request
    raise e
  File "c:\Users\takashi\.vscode\extensions\espressif.esp-idf-extension-1.5.1\esp_debug_adapter\debug_adapter\command_processor.py", line 70, in on_initialize_request
    self.da.adapter_init()
  File "c:\Users\takashi\.vscode\extensions\espressif.esp-idf-extension-1.5.1\esp_debug_adapter\debug_adapter\debug_adapter.py", line 328, in adapter_init
    raise e
  File "c:\Users\takashi\.vscode\extensions\espressif.esp-idf-extension-1.5.1\esp_debug_adapter\debug_adapter\debug_adapter.py", line 324, in adapter_init
    self.start_gdb()
  File "c:\Users\takashi\.vscode\extensions\espressif.esp-idf-extension-1.5.1\esp_debug_adapter\debug_adapter\debug_adapter.py", line 654, in start_gdb
    raise e
  File "c:\Users\takashi\.vscode\extensions\espressif.esp-idf-extension-1.5.1\esp_debug_adapter\debug_adapter\debug_adapter.py", line 642, in start_gdb
    self._gdb.exec_file_set(elf)
  File "c:\Users\takashi\.vscode\extensions\espressif.esp-idf-extension-1.5.1\esp_debug_adapter\debug_adapter\debug_backend\debug_backend\gdb.py", line 276, in exec_file_set
    res, _ = self._mi_cmd_run('-file-exec-and-symbols %s' % local_file_path)
  File "c:\Users\takashi\.vscode\extensions\espressif.esp-idf-extension-1.5.1\esp_debug_adapter\debug_adapter\debug_backend\debug_backend\gdb.py", line 206, in _mi_cmd_run
    raise DebuggerTargetStateTimeoutError(
debug_adapter.debug_backend.debug_backend.defs.DebuggerTargetStateTimeoutError: Failed to wait for completion of command "-file-exec-and-symbols c:/Users/takashi/esp/blink/build/blink.elf" / 5!
2023-02-28 09:29:29,044 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "response", "request_seq": 1, "success": false, "command": "initialize", "seq": 7, "message": "Failed to init Debug Adapter!", "body": {}}

[Debug Adapter]
2023-02-28 09:29:29,046 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Failed to wait for completion of command \"-file-exec-and-symbols c:/Users/takashi/esp/blink/build/blink.elf\" / 5!\n", "source": {}}, "seq": 8}

2023-02-28 09:29:29,046 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Failed to wait for completion of command \"-file-exec-and-symbols c:/Users/takashi/esp/blink/build/blink.elf\" / 5!\n", "source": {}}, "seq": 9}

[Debug Adapter]
2023-02-28 09:29:29,049 - Debug Adapter (ReaderThread) - DEBUG - read line: >>b'Content-Length: 79\\r\\n'<<

2023-02-28 09:29:29,049 - Debug Adapter (ReaderThread) - DEBUG - read line: >>b'\\r\\n'<<

[Debug Adapter]
2023-02-28 09:29:29,050 - Debug Adapter(Command Processor) - DEBUG - Got json: {
    "arguments": {
        "restart": false
    },
    "command": "disconnect",
    "seq": 2,
    "type": "request"
}
2023-02-28 09:29:29,050 - Debug Adapter (main) - DEBUG - Adapter is Stopping...
2023-02-28 09:29:29,050 - Debug Adapter (main) - DEBUG - Stopping target poller
2023-02-28 09:29:29,050 - Debug Adapter (main) - DEBUG - Closing the GDB process
2023-02-28 09:29:29,050 - Debug Adapter (main) - DEBUG - Closing the Socket
[Debug Adapter]
2023-02-28 09:29:29,050 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Got json: {\n    \"arguments\": {\n        \"restart\": false\n    },\n    \"command\": \"disconnect\",\n    \"seq\": 2,\n    \"type\": \"request\"\n}\n", "source": {}}, "seq": 10}

2023-02-28 09:29:29,050 - Debug Adapter (main) - DEBUG - Stopping of the Writer thread
2023-02-28 09:29:29,051 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Debug Adapter stopped\n", "source": {}}, "seq": 11}

[Debug Adapter]
2023-02-28 09:29:29,051 - Debug Adapter (main) - DEBUG - Stopping of the Reader thread
2023-02-28 09:29:29,051 - Debug Adapter (main) - DEBUG - Adapter is Stopped
DEBUG_ADAPTER_STOPPED
2023-02-28 09:29:29,051 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_STOPPED
2023-02-28 09:29:29,051 - Debug Adapter(Command Processor) - DEBUG - Processed command: disconnect
[Stopped] : ESP-IDF Debug Adapter
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
Have you tried increasing the `tmoScaleFactor` in the launch.json ? Something like `"tmoScaleFactor": 2` or bigger.

**Comment by matsujirushi** [comment]
Hi @brianignacio5 ,

very! It worked! !
Thank you very very much. 🤩

**launch.json:**

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "espidf",
      "name": "Launch",
      "request": "launch",
      "tmoScaleFactor": 2
    }
  ]
}
```
