### ISSUE TITLE
ESP32C3 Failed to start debug adapter (VSC-1104)

### ISSUE THREAD

**Issue by dalkvenk** [espressif/vscode-esp-idf-extension#961]
### Development Kit

ESP32C3 Dev Kit M1

### Module or chip used

ESP32C3

### Debug Adapter

Internal JTAG

### OpenOCD version

v0.11.0-esp32-20220706

### Operating System

MacOS

### Using an IDE ?

VS Code

### OpenOCD command line

openocd -f board/esp32c3-builtin.cfg

### JTAG Clock Speed

default

### ESP-IDF version

v5.0

### Problem Description

1. Use blink example from SDK
2. Flash the binary using internal JTAG using the command 
`openocd -f board/esp32c3-builtin.cfg -c "program_esp /Users/k.venkatraman/Cue-Hub/ESP-Projects/blink/build/blink.bin 0x10000 verify exit"`
3. **The internal JTAG debugger flashes the program successfully**.
4. Set up launch.json file as below
```
{
    "version": "0.2.0",
    "configurations": [
      {
        "type": "espidf",
        "name": "ESP-IDF OpenOcd",
        "request": "launch",
        "debugPort": 43474,
        "logLevel": 5,
        "mode": "auto",
        "tmoScaleFactor": 2,
      }
    ]
  }
```

5. Press F5 to start debugging.
6. Encounter the error: "Failed to connect to "remote 127.0.0.1:3333"

### Debug Logs

```shell
Logs from the Output console on VS Code:

[OpenOCD]
❌ Open On-Chip Debugger  v0.11.0-esp32-20220706 (2022-07-06-15:49)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
debug_level: 2

Error: couldn't bind tcl to socket on port 6666: Address already in use
[OpenOCD]
[Stopped] : OpenOCD Server
[Debug Adapter]
2023-04-24 10:42:56,606 - Debug Adapter (main) - DEBUG - START_TIME_2023_04_24_10-42-56
[Debug Adapter]
2023-04-24 10:42:56,606 - Debug Adapter (main) - DEBUG - Init errors:None
2023-04-24 10:42:56,606 - Debug Adapter (main) - INFO - Working directory: /
[Debug Adapter]
2023-04-24 10:42:56,606 - Debug Adapter (main) - INFO - Arguments: 
{   'app_flash_off': 65536,
    'board_type': None,
    'cmdfile': '/Users/k.venkatraman/Cue-Hub/ESP-Projects/blink/gdbinit',
    'core_file': (),
    'debug': 5,
    'developer_mode': 'none',
    'device_name': 'esp32c3',
    'elfpath': (   '/Users/k.venkatraman/Cue-Hub/ESP-Projects/blink/build/blink.elf',),
    'log_file': '/Users/k.venkatraman/Cue-Hub/ESP-Projects/blink/debug.log',
    'log_mult_files': None,
    'log_no_debug_console': None,
    'oocd': 'openocd',
    'oocd_args': None,
    'oocd_ip': 'localhost',
    'oocd_mode': 'connect_to_instance',
    'oocd_scripts': None,
    'port': 43474,
    'postmortem': False,
    'tmo_scale_factor': 2,
    'toolchain_prefix': 'riscv32-esp-elf-'}
[Debug Adapter]
DEBUG_ADAPTER_STARTED
2023-04-24 10:42:56,606 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_STARTED
2023-04-24 10:42:56,606 - Debug Adapter (main) - INFO - Starting. Cmd: /Users/k.venkatraman/.vscode/extensions/espressif.esp-idf-extension-1.6.1/esp_debug_adapter/debug_adapter_main.py -d 5 -e /Users/k.venkatraman/Cue-Hub/ESP-Projects/blink/build/blink.elf -l /Users/k.venkatraman/Cue-Hub/ESP-Projects/blink/debug.log -p 43474 -dn esp32c3 -a 0x10000 -t riscv32-esp-elf- -x /Users/k.venkatraman/Cue-Hub/ESP-Projects/blink/gdbinit -tsf 2

[Debug Adapter]
2023-04-24 10:42:56,610 - Debug Adapter (main) - INFO - Listening on port 43474
DEBUG_ADAPTER_READY2CONNECT
2023-04-24 10:42:56,610 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_READY2CONNECT
[Debug Adapter]
2023-04-24 10:42:56,611 - Debug Adapter (main) - DEBUG - Got connection
[Debug Adapter]
2023-04-24 10:42:56,611 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Debug adapter -> Extension: DEBUG_ADAPTER_STARTED\n", "source": {}}, "seq": 0}

[Debug Adapter]
2023-04-24 10:42:56,612 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Starting. Cmd: /Users/k.venkatraman/.vscode/extensions/espressif.esp-idf-extension-1.6.1/esp_debug_adapter/debug_adapter_main.py -d 5 -e /Users/k.venkatraman/Cue-Hub/ESP-Projects/blink/build/blink.elf -l /Users/k.venkatraman/Cue-Hub/ESP-Projects/blink/debug.log -p 43474 -dn esp32c3 -a 0x10000 -t riscv32-esp-elf- -x /Users/k.venkatraman/Cue-Hub/ESP-Projects/blink/gdbinit -tsf 2\n\n", "source": {}}, "seq": 1}

2023-04-24 10:42:56,612 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Listening on port 43474\n", "source": {}}, "seq": 2}

2023-04-24 10:42:56,612 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Debug adapter -> Extension: DEBUG_ADAPTER_READY2CONNECT\n", "source": {}}, "seq": 3}

[Debug Adapter]
2023-04-24 10:42:56,612 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Got connection\n", "source": {}}, "seq": 4}

[Debug Adapter]
2023-04-24 10:42:56,613 - Debug Adapter (ReaderThread) - DEBUG - read line: >>b'Content-Length: 453\\r\\n'<<

[Debug Adapter]
2023-04-24 10:42:56,613 - Debug Adapter (ReaderThread) - DEBUG - read line: >>b'\\r\\n'<<

[Debug Adapter]
2023-04-24 10:42:56,613 - Debug Adapter(Command Processor) - DEBUG - Got json: {
    "arguments": {
        "adapterID": "espidf",
        "clientID": "vscode",
        "clientName": "Visual Studio Code",
        "columnsStartAt1": true,
        "linesStartAt1": true,
        "locale": "en-us",
        "pathFormat": "path",
        "supportsArgsCanBeInterpretedByShell": true,
        "supportsInvalidatedEvent": true,
        "supportsMemoryReferences": true,
        "supportsProgressReporting": true,
        "supportsRunInTerminalRequest": true,
        "supportsVariablePaging": true,
        "supportsVariableType": true
    },
    "command": "initialize",
    "seq": 1,
    "type": "request"
}
[Debug Adapter]
2023-04-24 10:42:56,613 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Got json: {\n    \"arguments\": {\n        \"adapterID\": \"espidf\",\n        \"clientID\": \"vscode\",\n        \"clientName\": \"Visual Studio Code\",\n        \"columnsStartAt1\": true,\n        \"linesStartAt1\": true,\n        \"locale\": \"en-us\",\n        \"pathFormat\": \"path\",\n        \"supportsArgsCanBeInterpretedByShell\": true,\n        \"supportsInvalidatedEvent\": true,\n        \"supportsMemoryReferences\": true,\n        \"supportsProgressReporting\": true,\n        \"supportsRunInTerminalRequest\": true,\n        \"supportsVariablePaging\": true,\n        \"supportsVariableType\": true\n    },\n    \"command\": \"initialize\",\n    \"seq\": 1,\n    \"type\": \"request\"\n}\n", "source": {}}, "seq": 5}

[Debug Adapter]
2023-04-24 10:42:56,620 - Gdb - DEBUG - MI->: -gdb-set mi-async on
[Debug Adapter]
2023-04-24 10:42:56,961 - Gdb - DEBUG - MI<-:
[{'message': 'thread-group-added',
  'payload': {'id': 'i1'},
  'stream': 'stdout',
  'token': None,
  'type': 'notify'},
 {'message': 'done',
  'payload': None,
  'stream': 'stdout',
  'token': None,
  'type': 'result'}]
[Debug Adapter]
2023-04-24 10:42:56,961 - Gdb - INFO - NOTIFY: thread-group-added {'id': 'i1'}
2023-04-24 10:42:56,961 - Gdb - DEBUG - RESULT: done None
2023-04-24 10:42:56,961 - Gdb - DEBUG - MI->: -gdb-set logging file /var/folders/mf/j3g8lz8s4pj_ktqjjzw_bkdh0000gq/T/gdb_proc.log
[Debug Adapter]
2023-04-24 10:42:56,962 - Gdb - DEBUG - MI<-:
[{'message': 'done',
  'payload': None,
  'stream': 'stdout',
  'token': None,
  'type': 'result'}]
[Debug Adapter]
2023-04-24 10:42:56,962 - Gdb - DEBUG - RESULT: done None
2023-04-24 10:42:56,962 - Gdb - DEBUG - MI->: -gdb-set logging on
[Debug Adapter]
2023-04-24 10:42:56,962 - Gdb - DEBUG - MI<-:
[{'message': 'done',
  'payload': None,
  'stream': 'stdout',
  'token': None,
  'type': 'result'}]
[Debug Adapter]
2023-04-24 10:42:56,962 - Gdb - DEBUG - RESULT: done None
2023-04-24 10:42:56,962 - Gdb - DEBUG - MI->: -gdb-set arch riscv:rv32
[Debug Adapter]
2023-04-24 10:42:56,963 - Gdb - DEBUG - MI<-:
[{'message': None,
  'payload': 'The target architecture is set to \\"riscv:rv32\\".\\n',
  'stream': 'stdout',
  'type': 'console'},
 {'message': 'done',
  'payload': None,
  'stream': 'stdout',
  'token': None,
  'type': 'result'}]
[Debug Adapter]
2023-04-24 10:42:56,963 - Gdb - INFO - CONS: 'The target architecture is set to \\"riscv:rv32\\".\\n'
2023-04-24 10:42:56,963 - Gdb - DEBUG - RESULT: done None
[Debug Adapter]
2023-04-24 10:42:56,963 - Debug Adapter (main) - DEBUG - Created gdb object of type: GdbEsp32c3
[Debug Adapter]
2023-04-24 10:42:56,963 - Gdb - DEBUG - MI->: -file-exec-and-symbols /Users/k.venkatraman/Cue-Hub/ESP-Projects/blink/build/blink.elf
[Debug Adapter]
2023-04-24 10:42:56,963 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Created gdb object of type: GdbEsp32c3\n", "source": {}}, "seq": 6}

[Debug Adapter]
2023-04-24 10:42:56,989 - Gdb - DEBUG - MI<-:
[{'message': 'done',
  'payload': None,
  'stream': 'stdout',
  'token': None,
  'type': 'result'}]
[Debug Adapter]
2023-04-24 10:42:56,989 - Gdb - DEBUG - RESULT: done None
2023-04-24 10:42:56,989 - Gdb - DEBUG - Connecting to 127.0.0.1:3333
2023-04-24 10:42:56,989 - Gdb - DEBUG - MI->: -target-select remote 127.0.0.1:3333
[Debug Adapter]
2023-04-24 10:43:16,989 - Gdb - DEBUG - MI<-:
[{'message': 'error',
  'payload': {'msg': '127.0.0.1:3333: Operation timed out.'},
  'stream': 'stdout',
  'token': None,
  'type': 'result'}]
[Debug Adapter]
2023-04-24 10:43:16,989 - Gdb - DEBUG - RESULT: error {'msg': '127.0.0.1:3333: Operation timed out.'}
[Debug Adapter]
2023-04-24 10:43:16,990 - Debug Adapter (main) - ERROR - Failed to connect to "remote 127.0.0.1:3333"!
Traceback (most recent call last):
  File "/Users/k.venkatraman/.vscode/extensions/espressif.esp-idf-extension-1.6.1/esp_debug_adapter/debug_adapter/command_processor.py", line 52, in __call__
    on_request(protocol_message)
  File "/Users/k.venkatraman/.vscode/extensions/espressif.esp-idf-extension-1.6.1/esp_debug_adapter/debug_adapter/command_processor.py", line 75, in on_initialize_request
    raise e
  File "/Users/k.venkatraman/.vscode/extensions/espressif.esp-idf-extension-1.6.1/esp_debug_adapter/debug_adapter/command_processor.py", line 70, in on_initialize_request
    self.da.adapter_init()
  File "/Users/k.venkatraman/.vscode/extensions/espressif.esp-idf-extension-1.6.1/esp_debug_adapter/debug_adapter/debug_adapter.py", line 329, in adapter_init
    raise e
  File "/Users/k.venkatraman/.vscode/extensions/espressif.esp-idf-extension-1.6.1/esp_debug_adapter/debug_adapter/debug_adapter.py", line 325, in adapter_init
    self.start_gdb()
  File "/Users/k.venkatraman/.vscode/extensions/espressif.esp-idf-extension-1.6.1/esp_debug_adapter/debug_adapter/debug_adapter.py", line 659, in start_gdb
    raise e
  File "/Users/k.venkatraman/.vscode/extensions/espressif.esp-idf-extension-1.6.1/esp_debug_adapter/debug_adapter/debug_adapter.py", line 656, in start_gdb
    self._gdb.connect()
  File "/Users/k.venkatraman/.vscode/extensions/espressif.esp-idf-extension-1.6.1/esp_debug_adapter/debug_adapter/debug_backend/debug_backend/gdb.py", line 578, in connect
    self.target_select(remote_mode, self._remote_target, tmo=tmo)
  File "/Users/k.venkatraman/.vscode/extensions/espressif.esp-idf-extension-1.6.1/esp_debug_adapter/debug_adapter/debug_backend/debug_backend/gdb.py", line 258, in target_select
    raise DebuggerError('Failed to connect to "%s %s"!' % (tgt_type, tgt_params))
debug_adapter.debug_backend.debug_backend.defs.DebuggerError: Failed to connect to "remote 127.0.0.1:3333"!
[Debug Adapter]
2023-04-24 10:43:16,990 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "response", "request_seq": 1, "success": false, "command": "initialize", "seq": 7, "message": "Failed to init Debug Adapter!", "body": {}}

[Debug Adapter]
2023-04-24 10:43:16,991 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Failed to connect to \"remote 127.0.0.1:3333\"!\n", "source": {}}, "seq": 8}

2023-04-24 10:43:16,991 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Failed to connect to \"remote 127.0.0.1:3333\"!\n", "source": {}}, "seq": 9}

[Debug Adapter]
2023-04-24 10:43:17,024 - Debug Adapter (ReaderThread) - DEBUG - read line: >>b'Content-Length: 79\\r\\n'<<

2023-04-24 10:43:17,024 - Debug Adapter (ReaderThread) - DEBUG - read line: >>b'\\r\\n'<<

2023-04-24 10:43:17,024 - Debug Adapter(Command Processor) - DEBUG - Got json: {
    "arguments": {
        "restart": false
    },
    "command": "disconnect",
    "seq": 2,
    "type": "request"
}
2023-04-24 10:43:17,024 - Debug Adapter (main) - DEBUG - Adapter is Stopping...
2023-04-24 10:43:17,024 - Debug Adapter (main) - DEBUG - Stopping target poller
2023-04-24 10:43:17,024 - Debug Adapter (main) - DEBUG - Closing the GDB process
2023-04-24 10:43:17,024 - Debug Adapter (main) - DEBUG - Closing the Socket
2023-04-24 10:43:17,024 - Debug Adapter (main) - DEBUG - Stopping of the Writer thread
2023-04-24 10:43:17,024 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Got json: {\n    \"arguments\": {\n        \"restart\": false\n    },\n    \"command\": \"disconnect\",\n    \"seq\": 2,\n    \"type\": \"request\"\n}\n", "source": {}}, "seq": 10}

2023-04-24 10:43:17,025 - Debug Adapter (main) - DEBUG - Stopping of the Reader thread
2023-04-24 10:43:17,025 - Debug Adapter (main) - DEBUG - Adapter is Stopped
DEBUG_ADAPTER_STOPPED
2023-04-24 10:43:17,025 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_STOPPED
2023-04-24 10:43:17,025 - Debug Adapter(Command Processor) - DEBUG - Processed command: disconnect
[Stopped] : ESP-IDF Debug Adapter
```

### Expected behavior

Internal JTAG debugger successfully launches the debug session.

**Comment by brianignacio5** [comment]
Maybe the user needs to kill the openOCD used for flashing before, since it is probably still open ? Since the openocd is being executed outside the vscode extension the user needs to manually kill it. If the user wants to use the already existing openOCD session, it would need to launch the debug adapter manually too and change the mode to manual in launch.json

JTAG flashing is also possible from the extension and could reduce the issue of launch openocd again.

**Comment by brianignacio5** [comment]
Closing this issue for lack of response from the user.
