### ISSUE TITLE
DFU build failure is completely silent in the IDE (VSC-1106)

### ISSUE THREAD

**Issue by reinderien** [espressif/vscode-esp-idf-extension#966]
### OS

Windows

### Operating System version

Windows 11

### Visual Studio Code version

1.78.0

### ESP-IDF version

5.0.1

### Python version

3.8.7

### Doctor command output

The doctor command runs and then silently ends without telling me where the report went. Turns out it's on the clipboard... maybe you should tell someone about that.

```none
---------------------------------------------- ESP-IDF Extension for Visual Studio Code report ---------------------------------------------
OS win32 x64 10.0.22621 
System environment variable IDF_PYTHON_ENV_PATH 
 undefined 
System environment variable PATH 
 C:\Program Files\Python310\Scripts\;C:\Program Files\Python310\;C:\Program Files\Python38\Scripts\;C:\Program Files\Python38\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Pandoc\;C:\Program Files\MiKTeX\miktex\bin\x64\;C:\Program Files\PuTTY\;C:\Program Files\GitHub CLI\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft VS Code\bin;C:<HOMEPATH>\AppData\Local\Microsoft\WindowsApps;C:<HOMEPATH>\.dotnet\tools;C:\ProgramData\Miniconda3\Library\bin\graphviz;C:\Program Files\PostgreSQL\11\bin;C:\Program Files (x86)\WinMerge;C:\Program Files\jdk-17.0.1\bin;;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps 
System environment variable PYTHON 
 undefined 
Visual Studio Code version 1.78.0 
Visual Studio Code language en 
Visual Studio Code shell C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe 
ESP-IDF Extension version 1.6.2 
Workspace folder c:<HOMEPATH>\src\riptime\esp\firmware 
---------------------------------------------------- Extension configuration settings ------------------------------------------------------
ESP-ADF Path (idf.espAdfPath) ${env:ADF_PATH}
ESP-IDF Path (idf.espIdfPath) /ProgramData/esp-idf
ESP-MDF Path (idf.espMdfPath) ${env:MDF_PATH}
ESP-Matter Path (idf.espMatterPath) ${env:ESP_MATTER_PATH}
Custom extra paths (idf.customExtraPaths) /ProgramData/esp-idf-tools/tools/xtensa-esp-elf-gdb/11.2_20220823/xtensa-esp-elf-gdb/bin;C:/ProgramData/esp-idf-tools/tools/riscv32-esp-elf-gdb/11.2_20220823/riscv32-esp-elf-gdb/bin;C:/ProgramData/esp-idf-tools/tools/xtensa-esp32-elf/esp-2022r1-11.2.0/xtensa-esp32-elf/bin;C:/ProgramData/esp-idf-tools/tools/xtensa-esp32s2-elf/esp-2022r1-11.2.0/xtensa-esp32s2-elf/bin;C:/ProgramData/esp-idf-tools/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xtensa-esp32s3-elf/bin;C:/ProgramData/esp-idf-tools/tools/riscv32-esp-elf/esp-2022r1-11.2.0/riscv32-esp-elf/bin;C:/ProgramData/esp-idf-tools/tools/esp32ulp-elf/2.35_20220830/esp32ulp-elf/bin;C:/ProgramData/esp-idf-tools/tools/cmake/3.24.0/bin;C:/ProgramData/esp-idf-tools/tools/openocd-esp32/v0.11.0-esp32-20221026/openocd-esp32/bin;C:/ProgramData/esp-idf-tools/tools/ninja/1.10.2;C:/ProgramData/esp-idf-tools/tools/idf-exe/1.0.3;C:/ProgramData/esp-idf-tools/tools/ccache/4.6.2/ccache-4.6.2-windows-x86_64;C:/ProgramData/esp-idf-tools/tools/dfu-util/0.9/dfu-util-0.9-win64;C:/ProgramData/esp-idf-tools/tools/esp-rom-elfs/20220823
Custom extra vars (idf.customExtraVars)
    IDF_CCACHE_ENABLE: 1
    OPENOCD_SCRIPTS: /ProgramData/esp-idf-tools/tools/openocd-esp32/v0.11.0-esp32-20221026/openocd-esp32/share/openocd/scripts
    ESP_ROM_ELF_DIR: /ProgramData/esp-idf-tools/tools/esp-rom-elfs/20220823/
Virtual env Python Path (idf.pythonBinPath) /ProgramData/esp-idf-tools/python_env/idf5.0_py3.8_env/Scripts/python.exe
Serial port (idf.port) COM1
OpenOCD Configs (idf.openOcdConfigs) board/esp32c3-builtin.cfg
ESP-IDF Tools Path (idf.toolsPath) /ProgramData/esp-idf-tools
Git Path (idf.gitPath) /ProgramData/esp-idf-tools/tools/idf-git/2.30.1/cmd/git.exe
-------------------------------------------------------- Configurations access -------------------------------------------------------------
Access to ESP-ADF Path (idf.espAdfPath) false
Access to ESP-IDF Path (idf.espIdfPath) true
Access to ESP-MDF Path (idf.espMdfPath) false
Access to ESP-Matter Path (idf.espMatterPath) false
Access to ESP-IDF Custom extra paths
Access to /ProgramData/esp-idf-tools/tools/xtensa-esp-elf-gdb/11.2_20220823/xtensa-esp-elf-gdb/bin: true
Access to C:/ProgramData/esp-idf-tools/tools/riscv32-esp-elf-gdb/11.2_20220823/riscv32-esp-elf-gdb/bin: true
Access to C:/ProgramData/esp-idf-tools/tools/xtensa-esp32-elf/esp-2022r1-11.2.0/xtensa-esp32-elf/bin: true
Access to C:/ProgramData/esp-idf-tools/tools/xtensa-esp32s2-elf/esp-2022r1-11.2.0/xtensa-esp32s2-elf/bin: true
Access to C:/ProgramData/esp-idf-tools/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xtensa-esp32s3-elf/bin: true
Access to C:/ProgramData/esp-idf-tools/tools/riscv32-esp-elf/esp-2022r1-11.2.0/riscv32-esp-elf/bin: true
Access to C:/ProgramData/esp-idf-tools/tools/esp32ulp-elf/2.35_20220830/esp32ulp-elf/bin: true
Access to C:/ProgramData/esp-idf-tools/tools/cmake/3.24.0/bin: true
Access to C:/ProgramData/esp-idf-tools/tools/openocd-esp32/v0.11.0-esp32-20221026/openocd-esp32/bin: true
Access to C:/ProgramData/esp-idf-tools/tools/ninja/1.10.2: true
Access to C:/ProgramData/esp-idf-tools/tools/idf-exe/1.0.3: true
Access to C:/ProgramData/esp-idf-tools/tools/ccache/4.6.2/ccache-4.6.2-windows-x86_64: true
Access to C:/ProgramData/esp-idf-tools/tools/dfu-util/0.9/dfu-util-0.9-win64: true
Access to C:/ProgramData/esp-idf-tools/tools/esp-rom-elfs/20220823: true
Access to Virtual env Python Path (idf.pythonBinPath) true
Access to CMake in environment PATH undefined
Access to Ninja in environment PATH undefined
Access to ESP-IDF Tools Path (idf.toolsPath) true
-------------------------------------------------------- Configurations has spaces -------------------------------------------------------------
Spaces in system environment Path true
Spaces in ESP-ADF Path (idf.espAdfPath) false
Spaces in ESP-IDF Path (idf.espIdfPath) false
Spaces in ESP-MDF Path (idf.espMdfPath) false
Spaces in ESP-Matter Path (idf.espMatterPath) false
Spaces in ESP-IDF Custom extra paths
Spaces in /ProgramData/esp-idf-tools/tools/xtensa-esp-elf-gdb/11.2_20220823/xtensa-esp-elf-gdb/bin: false
Spaces in C:/ProgramData/esp-idf-tools/tools/riscv32-esp-elf-gdb/11.2_20220823/riscv32-esp-elf-gdb/bin: false
Spaces in C:/ProgramData/esp-idf-tools/tools/xtensa-esp32-elf/esp-2022r1-11.2.0/xtensa-esp32-elf/bin: false
Spaces in C:/ProgramData/esp-idf-tools/tools/xtensa-esp32s2-elf/esp-2022r1-11.2.0/xtensa-esp32s2-elf/bin: false
Spaces in C:/ProgramData/esp-idf-tools/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xtensa-esp32s3-elf/bin: false
Spaces in C:/ProgramData/esp-idf-tools/tools/riscv32-esp-elf/esp-2022r1-11.2.0/riscv32-esp-elf/bin: false
Spaces in C:/ProgramData/esp-idf-tools/tools/esp32ulp-elf/2.35_20220830/esp32ulp-elf/bin: false
Spaces in C:/ProgramData/esp-idf-tools/tools/cmake/3.24.0/bin: false
Spaces in C:/ProgramData/esp-idf-tools/tools/openocd-esp32/v0.11.0-esp32-20221026/openocd-esp32/bin: false
Spaces in C:/ProgramData/esp-idf-tools/tools/ninja/1.10.2: false
Spaces in C:/ProgramData/esp-idf-tools/tools/idf-exe/1.0.3: false
Spaces in C:/ProgramData/esp-idf-tools/tools/ccache/4.6.2/ccache-4.6.2-windows-x86_64: false
Spaces in C:/ProgramData/esp-idf-tools/tools/dfu-util/0.9/dfu-util-0.9-win64: false
Spaces in C:/ProgramData/esp-idf-tools/tools/esp-rom-elfs/20220823: false
Spaces in Virtual env Python Path (idf.pythonBinPath) false
Spaces in ESP-IDF Tools Path (idf.toolsPath) false
----------------------------------------------------------- Executables Versions -----------------------------------------------------------
Git version 2.30.1.windows.1
ESP-IDF version 5.0.1
Python version 3.8.7
Python's pip version 23.1.2
-------------------------------------------------- Project configuration settings ----------------------------------------------------------
-------------------------------------------------- Python packages in idf.pythonBinPath ----------------------------------------------------
bitstring version: 4.0.2
CacheControl version: 0.12.11
certifi version: 2022.12.7
cffi version: 1.15.1
charset-normalizer version: 3.1.0
click version: 8.0.4
colorama version: 0.4.6
construct version: 2.10.68
contextlib2 version: 21.6.0
cryptography version: 36.0.2
ecdsa version: 0.18.0
esp-coredump version: 1.5.0
esptool version: 4.5.1
freertos-gdb version: 1.0.2
future version: 0.18.2
gcovr version: 6.0
idf-component-manager version: 1.2.2
idna version: 3.4
Jinja2 version: 3.0.3
kconfiglib version: 14.1.0
lockfile version: 0.12.2
lxml version: 4.9.2
MarkupSafe version: 2.1.2
msgpack version: 1.0.5
packaging version: 23.1
pip version: 23.1.2
psutil version: 5.9.5
pycparser version: 2.21
pyelftools version: 0.27
pygdbmi version: 0.9.0.2
Pygments version: 2.15.1
pyparsing version: 3.0.9
pyserial version: 3.5
pywin32 version: 306
PyYAML version: 6.0
reedsolo version: 1.6.0
requests version: 2.30.0
requests-file version: 1.5.1
requests-toolbelt version: 1.0.0
schema version: 0.7.5
setuptools version: 67.7.2
six version: 1.16.0
tqdm version: 4.65.0
urllib3 version: 1.26.15
websocket-client version: 1.5.1
wheel version: 0.37.1
windows-curses version: 2.3.1
xmlrunner version: 1.7.7
---------------------------------------------------- Check ESP-IDF python requirements.txt -------------------------------------------------
Check ESP-IDF Python packages Python requirements are satisfied.
---------------------------------------------------- Check extension requirements.txt ------------------------------------------------------
Check Extension Python packages Python requirements are satisfied.
---------------------------------------------------- Check ESP-IDF debug adapter requirements.txt ------------------------------------------
Check Debug AdapterPython packages Python requirements are satisfied.
----------------------------------------------------------- Latest error -----------------------------------------------------------------
Latest error at Unknown error in ESP-IDF doctor command
--------------------------------------------------------------------------------------------------------------------------------------------
```

### Extension

Your prompt is wrong. It asks for `%USERPROFILE%.vscode\` when it should be `%USERPROFILE%\.vscode\`.

In `.vscode\extensions\espressif.esp-idf-extension-1.6.2` the log shows (among other things)

```json
{"message":"Cannot access filePath: c:\\Users\\gtoom\\src\\riptime\\esp\\devboard\\build\\CMakeCache.txt","stack":"Error: ENOENT: no such file or directory, access 'c:\\Users\\gtoom\\src\\riptime\\esp\\devboard\\build\\CMakeCache.txt'\n\tat Object.accessSync (node:fs:258:3)\n\tat t.accessSync (node:electron/js2c/asar_bundle:2:8282)\n\tat De (\\dist\\extension.js:2:1192177)\n\tat \\dist\\extension.js:2:1465722\n\tat Generator.next (<anonymous>)\n\tat s (\\dist\\extension.js:2:1459208)","level":"error","timestamp":"2023-05-06T20:52:07.495Z"}
{"user":true,"level":"warn","message":"There is no CMakeCache.txt. Please try to delete the build directory manually.","timestamp":"2023-05-06T20:52:07.495Z"}
{"message":"Open On-Chip Debugger v0.11.0-esp32-20221026 (2022-10-26-14:48)\r\nLicensed under GNU GPL v2\r\nFor bug reports, read\r\n\thttp://openocd.org/doc/doxygen/bugs.html\r\n","stack":"Error: Open On-Chip Debugger v0.11.0-esp32-20221026 (2022-10-26-14:48)\r\nLicensed under GNU GPL v2\r\nFor bug reports, read\r\n\thttp://openocd.org/doc/doxygen/bugs.html\r\n\n\tat \\dist\\extension.js:2:1195081\n\tat ChildProcess.exithandler (node:child_process:401:7)\n\tat ChildProcess.emit (node:events:513:28)\n\tat maybeClose (node:internal/child_process:1093:16)\n\tat Socket.<anonymous> (node:internal/child_process:451:11)\n\tat Socket.emit (node:events:513:28)\n\tat Pipe.<anonymous> (node:net:757:14)","level":"error","timestamp":"2023-05-06T21:03:54.033Z"}

{"message":"ESP Insights Project commit: 203a87f\r\n","stack":"Error: ESP Insights Project commit: 203a87f\r\n\n\tat Ot.printError (\\dist\\extension.js:2:1220603)\n\tat Socket.<anonymous> (\\dist\\extension.js:2:1220079)\n\tat Socket.emit (node:events:513:28)\n\tat addChunk (node:internal/streams/readable:315:12)\n\tat readableAddChunk (node:internal/streams/readable:289:9)\n\tat Readable.push (node:internal/streams/readable:228:10)\n\tat Pipe.onStreamRead (node:internal/stream_base_commons:190:23)","level":"error","timestamp":"2023-05-06T22:04:33.220Z"}
{"message":"ESP RainMaker Project commit: cc861bf\r\n","stack":"Error: ESP RainMaker Project commit: cc861bf\r\n\n\tat Ot.printError (\\dist\\extension.js:2:1220603)\n\tat Socket.<anonymous> (\\dist\\extension.js:2:1220079)\n\tat Socket.emit (node:events:513:28)\n\tat addChunk (node:internal/streams/readable:315:12)\n\tat readableAddChunk (node:internal/streams/readable:289:9)\n\tat Readable.push (node:internal/streams/readable:228:10)\n\tat Pipe.onStreamRead (node:internal/stream_base_commons:190:23)","level":"error","timestamp":"2023-05-06T22:04:33.547Z"}
{"user":true,"level":"warn","message":"The selected device target \"esp32c3\" is not compatible for DFU, as a result the DFU.bin was not created.","timestamp":"2023-05-06T23:07:57.813Z"}
{"user":true,"message":"Wait for ESP-IDF build or flash to finish","stack":"Error: One_Task_At_A_Time\n\tat l (\\dist\\extension.js:2:1398230)\n\tat l.next (<anonymous>)\n\tat \\dist\\extension.js:2:1398529\n\tat new Promise (<anonymous>)\n\tat No (\\dist\\extension.js:2:1398265)\n\tat \\dist\\extension.js:2:1526731\n\tat Generator.next (<anonymous>)\n\tat \\dist\\extension.js:2:1459406\n\tat new Promise (<anonymous>)\n\tat $s (\\dist\\extension.js:2:1459151)\n\tat \\dist\\extension.js:2:1526659\n\tat D.d (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:98:45036)\n\tat D.withProgress (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:98:44879)\n\tat Object.withProgress (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:116:34519)\n\tat \\dist\\extension.js:2:1526555\n\tat Generator.next (<anonymous>)\n\tat \\dist\\extension.js:2:1459406\n\tat new Promise (<anonymous>)\n\tat $s (\\dist\\extension.js:2:1459151)\n\tat \\dist\\extension.js:2:1526503\n\tat Ie.perform (\\dist\\extension.js:2:1190841)\n\tat ba (\\dist\\extension.js:2:1526485)\n\tat \\dist\\extension.js:2:1460354\n\tat e.ExtHostCommands.h (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:98:125315)\n\tat e.ExtHostCommands.$executeContributedCommand (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:98:126218)\n\tat a.N (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:110:11620)\n\tat a.M (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:110:11338)\n\tat a.H (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:110:10431)\n\tat a.G (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:110:9412)\n\tat \\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:110:8200\n\tat v.invoke (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:63:145)\n\tat h.deliver (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:63:2121)\n\tat i.fire (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:63:1729)\n\tat g.fire (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:72:14852)\n\tat \\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:126:32403\n\tat v.invoke (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:63:145)\n\tat h.deliver (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:63:2121)\n\tat i.fire (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:63:1729)\n\tat g.fire (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:72:14852)\n\tat MessagePortMain.<anonymous> (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:126:30529)\n\tat MessagePortMain.emit (node:events:513:28)\n\tat MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)","level":"error","timestamp":"2023-05-06T23:22:28.113Z"}

{"user":true,"message":"No DFU capable USB device available found","stack":"Error: NO_DFU_DEVICES_FOUND\n\tat \\dist\\extension.js:2:1530232\n\tat Generator.next (<anonymous>)\n\tat s (\\dist\\extension.js:2:1398641)","level":"error","timestamp":"2023-05-07T00:24:37.094Z"}

{"message":"Cannot access filePath: ${env:ADF_PATH}","stack":"Error: ENOENT: no such file or directory, access '${env:ADF_PATH}'\n\tat Object.accessSync (node:fs:258:3)\n\tat t.accessSync (node:electron/js2c/asar_bundle:2:8282)\n\tat De (\\dist\\extension.js:2:1192177)\n\tat \\dist\\extension.js:2:1504444\n\tat Generator.next (<anonymous>)\n\tat \\dist\\extension.js:2:1373621\n\tat new Promise (<anonymous>)\n\tat ro (\\dist\\extension.js:2:1373366)\n\tat \\dist\\extension.js:2:1504286\n\tat \\dist\\extension.js:2:1505410\n\tat Generator.next (<anonymous>)\n\tat s (\\dist\\extension.js:2:1386977)","level":"error","timestamp":"2023-05-07T00:31:12.870Z"}
{"message":"Cannot access filePath: ${env:MDF_PATH}","stack":"Error: ENOENT: no such file or directory, access '${env:MDF_PATH}'\n\tat Object.accessSync (node:fs:258:3)\n\tat t.accessSync (node:electron/js2c/asar_bundle:2:8282)\n\tat De (\\dist\\extension.js:2:1192177)\n\tat \\dist\\extension.js:2:1504622\n\tat Generator.next (<anonymous>)\n\tat \\dist\\extension.js:2:1373621\n\tat new Promise (<anonymous>)\n\tat ro (\\dist\\extension.js:2:1373366)\n\tat \\dist\\extension.js:2:1504286\n\tat \\dist\\extension.js:2:1505410\n\tat Generator.next (<anonymous>)\n\tat s (\\dist\\extension.js:2:1386977)","level":"error","timestamp":"2023-05-07T00:31:12.870Z"}
{"message":"Cannot access filePath: ${env:ESP_MATTER_PATH}","stack":"Error: ENOENT: no such file or directory, access '${env:ESP_MATTER_PATH}'\n\tat Object.accessSync (node:fs:258:3)\n\tat t.accessSync (node:electron/js2c/asar_bundle:2:8282)\n\tat De (\\dist\\extension.js:2:1192177)\n\tat \\dist\\extension.js:2:1504714\n\tat Generator.next (<anonymous>)\n\tat \\dist\\extension.js:2:1373621\n\tat new Promise (<anonymous>)\n\tat ro (\\dist\\extension.js:2:1373366)\n\tat \\dist\\extension.js:2:1504286\n\tat \\dist\\extension.js:2:1505410\n\tat Generator.next (<anonymous>)\n\tat s (\\dist\\extension.js:2:1386977)","level":"error","timestamp":"2023-05-07T00:31:12.870Z"}
```

### Description

The log explains most of it, but I believe there to be a hardware problem with my host board that prevents USB from showing up. The problem in the IDE is that it silently fails and doesn't tell me a single thing about this condition, and I need to hunt through the logs to see what's going on.

### Debug Message

In the extension host log I'm getting

```none
2023-05-06 20:28:30.469 [error] TypeError: Cannot read properties of undefined (reading 'start')
	at c:\Users\gtoom\.vscode\extensions\espressif.esp-idf-extension-1.6.2\dist\extension.js:2:1534619
	at Generator.next (<anonymous>)
	at s (c:\Users\gtoom\.vscode\extensions\espressif.esp-idf-extension-1.6.2\dist\extension.js:2:1459208)
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by reinderien** [comment]
Typo; that should read

`%USERPROFILE%\.vscode\`.

**Comment by reinderien** [comment]
In the extension host log I'm also getting

```none
2023-05-06 20:28:30.469 [error] TypeError: Cannot read properties of undefined (reading 'start')
	at c:\Users\gtoom\.vscode\extensions\espressif.esp-idf-extension-1.6.2\dist\extension.js:2:1534619
	at Generator.next (<anonymous>)
	at s (c:\Users\gtoom\.vscode\extensions\espressif.esp-idf-extension-1.6.2\dist\extension.js:2:1459208)
```

**Comment by radurentea** [comment]
hi @reinderien,

Thank you for the report. I will work on a fix.

I see that you are using a C3 board, but DFU is being supported only for the S2 and S3 boards.

**Comment by reinderien** [comment]
@radurentea I appreciate that. And yes, selecting DFU was my mistake - the board is working quite well with JTAG now. The bug is about the errors above and the IDE's ability to report them in the UI. Thank you and let me know if you need any more information.

**Comment by radurentea** [comment]
The issue is that the error is not being shown in the Output channel.
As a work around for now, I suggest you to activate the notification messages (they are hidden by default) by doing the following steps:
1) Open your project folder
2) Go into .vscode
3) Open settings.json
4) Add `"idf.notificationSilentMode": false, `
